//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SquirlearnWA.tamanoSOAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://item.squirlearnws.mycompany.com/", ConfigurationName="tamanoSOAP.Tamano")]
    public interface Tamano {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Tamano/listarTodosTamanoRequest", ReplyAction="http://item.squirlearnws.mycompany.com/Tamano/listarTodosTamanoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SquirlearnWA.tamanoSOAP.listarTodosTamanoResponse listarTodosTamano(SquirlearnWA.tamanoSOAP.listarTodosTamanoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Tamano/listarTodosTamanoRequest", ReplyAction="http://item.squirlearnws.mycompany.com/Tamano/listarTodosTamanoResponse")]
        System.Threading.Tasks.Task<SquirlearnWA.tamanoSOAP.listarTodosTamanoResponse> listarTodosTamanoAsync(SquirlearnWA.tamanoSOAP.listarTodosTamanoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Tamano/obtenerPorIdTamanoRequest", ReplyAction="http://item.squirlearnws.mycompany.com/Tamano/obtenerPorIdTamanoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SquirlearnWA.tamanoSOAP.obtenerPorIdTamanoResponse obtenerPorIdTamano(SquirlearnWA.tamanoSOAP.obtenerPorIdTamanoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Tamano/obtenerPorIdTamanoRequest", ReplyAction="http://item.squirlearnws.mycompany.com/Tamano/obtenerPorIdTamanoResponse")]
        System.Threading.Tasks.Task<SquirlearnWA.tamanoSOAP.obtenerPorIdTamanoResponse> obtenerPorIdTamanoAsync(SquirlearnWA.tamanoSOAP.obtenerPorIdTamanoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://item.squirlearnws.mycompany.com/")]
    public partial class tamanoDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private int tamanoIdField;
        
        private bool tamanoIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int tamanoId {
            get {
                return this.tamanoIdField;
            }
            set {
                this.tamanoIdField = value;
                this.RaisePropertyChanged("tamanoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tamanoIdSpecified {
            get {
                return this.tamanoIdFieldSpecified;
            }
            set {
                this.tamanoIdFieldSpecified = value;
                this.RaisePropertyChanged("tamanoIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosTamano", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class listarTodosTamanoRequest {
        
        public listarTodosTamanoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosTamanoResponse", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class listarTodosTamanoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://item.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SquirlearnWA.tamanoSOAP.tamanoDto[] @return;
        
        public listarTodosTamanoResponse() {
        }
        
        public listarTodosTamanoResponse(SquirlearnWA.tamanoSOAP.tamanoDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdTamano", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class obtenerPorIdTamanoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://item.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerPorIdTamanoRequest() {
        }
        
        public obtenerPorIdTamanoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdTamanoResponse", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class obtenerPorIdTamanoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://item.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SquirlearnWA.tamanoSOAP.tamanoDto @return;
        
        public obtenerPorIdTamanoResponse() {
        }
        
        public obtenerPorIdTamanoResponse(SquirlearnWA.tamanoSOAP.tamanoDto @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TamanoChannel : SquirlearnWA.tamanoSOAP.Tamano, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TamanoClient : System.ServiceModel.ClientBase<SquirlearnWA.tamanoSOAP.Tamano>, SquirlearnWA.tamanoSOAP.Tamano {
        
        public TamanoClient() {
        }
        
        public TamanoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TamanoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TamanoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TamanoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SquirlearnWA.tamanoSOAP.listarTodosTamanoResponse SquirlearnWA.tamanoSOAP.Tamano.listarTodosTamano(SquirlearnWA.tamanoSOAP.listarTodosTamanoRequest request) {
            return base.Channel.listarTodosTamano(request);
        }
        
        public SquirlearnWA.tamanoSOAP.tamanoDto[] listarTodosTamano() {
            SquirlearnWA.tamanoSOAP.listarTodosTamanoRequest inValue = new SquirlearnWA.tamanoSOAP.listarTodosTamanoRequest();
            SquirlearnWA.tamanoSOAP.listarTodosTamanoResponse retVal = ((SquirlearnWA.tamanoSOAP.Tamano)(this)).listarTodosTamano(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SquirlearnWA.tamanoSOAP.listarTodosTamanoResponse> SquirlearnWA.tamanoSOAP.Tamano.listarTodosTamanoAsync(SquirlearnWA.tamanoSOAP.listarTodosTamanoRequest request) {
            return base.Channel.listarTodosTamanoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SquirlearnWA.tamanoSOAP.listarTodosTamanoResponse> listarTodosTamanoAsync() {
            SquirlearnWA.tamanoSOAP.listarTodosTamanoRequest inValue = new SquirlearnWA.tamanoSOAP.listarTodosTamanoRequest();
            return ((SquirlearnWA.tamanoSOAP.Tamano)(this)).listarTodosTamanoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SquirlearnWA.tamanoSOAP.obtenerPorIdTamanoResponse SquirlearnWA.tamanoSOAP.Tamano.obtenerPorIdTamano(SquirlearnWA.tamanoSOAP.obtenerPorIdTamanoRequest request) {
            return base.Channel.obtenerPorIdTamano(request);
        }
        
        public SquirlearnWA.tamanoSOAP.tamanoDto obtenerPorIdTamano(int id) {
            SquirlearnWA.tamanoSOAP.obtenerPorIdTamanoRequest inValue = new SquirlearnWA.tamanoSOAP.obtenerPorIdTamanoRequest();
            inValue.id = id;
            SquirlearnWA.tamanoSOAP.obtenerPorIdTamanoResponse retVal = ((SquirlearnWA.tamanoSOAP.Tamano)(this)).obtenerPorIdTamano(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SquirlearnWA.tamanoSOAP.obtenerPorIdTamanoResponse> SquirlearnWA.tamanoSOAP.Tamano.obtenerPorIdTamanoAsync(SquirlearnWA.tamanoSOAP.obtenerPorIdTamanoRequest request) {
            return base.Channel.obtenerPorIdTamanoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SquirlearnWA.tamanoSOAP.obtenerPorIdTamanoResponse> obtenerPorIdTamanoAsync(int id) {
            SquirlearnWA.tamanoSOAP.obtenerPorIdTamanoRequest inValue = new SquirlearnWA.tamanoSOAP.obtenerPorIdTamanoRequest();
            inValue.id = id;
            return ((SquirlearnWA.tamanoSOAP.Tamano)(this)).obtenerPorIdTamanoAsync(inValue);
        }
    }
}
