DELIMITER $
-- -------------------------------------------------------------------------------------------
-- REPORTES
-- -------------------------------------------------------------------------------------------

/*REPORTE CORRESPONDIENTE AL RF20 - Reporte Mejores Calificaciones*/
-- DROP PROCEDURE IF EXISTS  REPORTE_CALIFICACIONES;
-- drop procedure REPORTE_CALIFICACIONES;
CREATE PROCEDURE REPORTE_CALIFICACIONES()
BEGIN
	SELECT 	s.PERSONA_ID, 
    s.NOMBRES, 
    s.PRIMER_APELLIDO,
    s.CODIGO , 
    ROUND(AVG(p.CALIFICACION),1) as CALIFICACION,
    CASE 
            WHEN AVG(p.CALIFICACION) >= 4 THEN 'EXCELENTE'
            WHEN AVG(p.CALIFICACION) >= 3 THEN 'BUENO'
            WHEN AVG(p.CALIFICACION) >= 2 THEN 'REGULAR'
            WHEN AVG(p.CALIFICACION) >= 1 THEN 'BAJO'
            ELSE 'MUY BAJO'
        END as CATEGORIA
    FROM PERSONAS s
    JOIN PUBLICACIONES p ON s.PERSONA_ID = p.PERSONA_ID
    GROUP BY s.PERSONA_ID
    ORDER BY CALIFICACION DESC;
END$

/*REPORTE CORRESPONDIENTE AL RF19 - Reporte Ventas y alquileres */
-- DROP PROCEDURE IF EXISTS  REPORTE_VENTA;
drop procedure REPORTE_VENTA;
CREATE PROCEDURE REPORTE_VENTA( IN _persona INT)
BEGIN
	SELECT c.TRANSACCION_ID, 
    i.NOMBRE,
    c.FECHA_EMISION,
    c.PERSONA_ID_PERSONA as comprador,
    d.PRECIO
    FROM PUBLICACIONES p
    JOIN ITEMS i ON i.ITEM_ID = p.ITEM_ID_ITEM
    JOIN DETALLES_COMPROBANTES d ON d.ITEM_ID_ITEM = i.ITEM_ID
    JOIN COMPROBANTES c ON c.COMPROBANTE_ID = d.COMPROBANTE_ID_COMPROBANTE
    WHERE p.PERSONA_ID = _persona;
END$
 drop procedure REPORTE_ALQUILER;

CREATE PROCEDURE REPORTE_ALQUILER(IN _persona INT, IN _inicio DATE, IN _fin DATE)
BEGIN
	SELECT c.TRANSACCION_ID, 
    i.NOMBRE,
    c.FECHA_EMISION,
    c.PERSONA_ID_PERSONA as comprador,
    d.PRECIO
    FROM PUBLICACIONES p
    JOIN ITEMS i ON i.ITEM_ID = p.ITEM_ID_ITEM
    JOIN ALQUILERES a ON a.ITEM_ID = i.ITEM_ID
    JOIN DETALLES_COMPROBANTES d ON a.ALQUILER_ID = d.ALQUILER_ID_ALQUILER
    JOIN COMPROBANTES c ON c.COMPROBANTE_ID = d.COMPROBANTE_ID_COMPROBANTE
    WHERE p.PERSONA_ID = _persona AND c.FECHA_EMISION >= _inicio AND c.FECHA_EMISION <= _fin; 
END$

/*REPORTE CORRESPONDIENTE AL RF18 - Reporte mas transacciones */
-- DROP PROCEDURE IF EXISTS  REPORTE_VENTA;
-- drop procedure REPORTE_VENTA;
CREATE PROCEDURE REPORTE_TRANSACCCIONES_OFERTADOR( IN _inicio DATE, IN _fin DATE)
BEGIN
	SELECT s.PERSONA_ID ,
    s.NOMBRES,
    s. PRIMER_APELLIDO, 
    s.CODIGO,
    COUNT(*) as NUM_TRANSACCIONES,
    SUM(d.PRECIO) as TOTAL 
    FROM PUBLICACIONES p
    JOIN ITEMS i ON i.ITEM_ID = p.ITEM_ID_ITEM
    JOIN ALQUILERES a ON a.ITEM_ID = i.ITEM_ID 
    JOIN DETALLES_COMPROBANTES d ON d.ITEM_ID_ITEM = i.ITEM_ID AND a.ALQUILER_ID = d.ALQUILER_ID_ALQUILER
    JOIN COMPROBANTES c ON c.COMPROBANTE_ID = d.COMPROBANTE_ID_COMPROBANTE
    JOIN PERSONAS s ON s.PERSONA_ID = p.PERSONA_ID
    WHERE c.FECHA_EMISION >= _inicio AND c.FECHA_EMISION <= _fin
    GROUP BY p.PERSONA_ID; 
END$

CREATE PROCEDURE REPORTE_TRANSACCCIONES_RECEPTOR( IN _inicio DATE, IN _fin DATE)
BEGIN
	SELECT s.PERSONA_ID ,
    s.NOMBRES,
    s. PRIMER_APELLIDO, 
    s.CODIGO,
    COUNT(*) as NUM_TRANSACCIONES,
    SUM(c.MONTO) as TOTAL
	FROM PERSONAS s
    JOIN COMPROBANTES c ON c.PERSONA_ID_PERSONA = s.PERSONA_ID
    WHERE c.FECHA_EMISION >= _inicio AND c.FECHA_EMISION <= _fin
    GROUP BY s.PERSONA_ID; 
END$
