-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`colores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`colores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`colores` (
  `COLOR_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(100) NOT NULL,
  `FECHA_CREACION` DATETIME NOT NULL,
  `USUARIO_CREACION` VARCHAR(100) NOT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICACION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`COLOR_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`condiciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`condiciones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`condiciones` (
  `CONDICION_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(100) NOT NULL,
  `FECHA_CREACION` DATETIME NOT NULL,
  `USUARIO_CREACION` VARCHAR(100) NOT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICACION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`CONDICION_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`estados_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estados_items` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estados_items` (
  `ESTADOITEM_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(100) NOT NULL,
  `FECHA_CREACION` DATETIME NOT NULL,
  `USUARIO_CREACION` VARCHAR(100) NOT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICACION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ESTADOITEM_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`formatos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`formatos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`formatos` (
  `FORMATO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(100) NOT NULL,
  `FECHA_CREACION` DATETIME NOT NULL,
  `USUARIO_CREACION` VARCHAR(100) NOT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICACION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`FORMATO_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categorias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `CATEGORIA_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(100) NOT NULL,
  `FECHA_CREACION` DATETIME NOT NULL,
  `USUARIO_CREACION` VARCHAR(100) NOT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICACION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`CATEGORIA_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`subcategorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`subcategorias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`subcategorias` (
  `SUBCATEGORIA_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(100) NOT NULL,
  `CATEGORIA_ID` INT NOT NULL,
  `FECHA_CREACION` DATETIME NOT NULL,
  `USUARIO_CREACION` VARCHAR(100) NOT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICACION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`SUBCATEGORIA_ID`, `CATEGORIA_ID`),
  INDEX `fk_SUBCATEGORIA_CATEGORIA1_idx` (`CATEGORIA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_SUBCATEGORIA_CATEGORIA1`
    FOREIGN KEY (`CATEGORIA_ID`)
    REFERENCES `mydb`.`categorias` (`CATEGORIA_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`tamanos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tamanos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tamanos` (
  `TAMANO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(100) NOT NULL,
  `FECHA_CREACION` DATETIME NOT NULL,
  `USUARIO_CREACION` VARCHAR(100) NOT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICACION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`TAMANO_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`items` ;

CREATE TABLE IF NOT EXISTS `mydb`.`items` (
  `ITEM_ID` INT NOT NULL AUTO_INCREMENT,
  `PRECIO` DECIMAL(10,2) NOT NULL,
  `NOMBRE` VARCHAR(100) NOT NULL,
  `DESCRIPCION` VARCHAR(300) NOT NULL,
  `ES_VENTA` TINYINT(3) UNSIGNED ZEROFILL NOT NULL,
  `COLOR_ID` INT NOT NULL,
  `ESTADO_ITEM_ID` INT NOT NULL,
  `CONDICION_ID` INT NOT NULL,
  `TAMANO_ID` INT NOT NULL,
  `FORMATO_ID` INT NOT NULL,
  `subcategoria_ID_SUBCATEGORIA` INT NOT NULL,
  `subcategoria_CATEGORIA_ID` INT NOT NULL,
  PRIMARY KEY (`ITEM_ID`),
  INDEX `fk_ITEM_COLOR1_idx` (`COLOR_ID` ASC) VISIBLE,
  INDEX `fk_ITEM_ESTADO_ITEM1_idx` (`ESTADO_ITEM_ID` ASC) VISIBLE,
  INDEX `fk_ITEM_CONDICION1_idx` (`CONDICION_ID` ASC) VISIBLE,
  INDEX `fk_ITEM_TAMANO1_idx` (`TAMANO_ID` ASC) VISIBLE,
  INDEX `fk_ITEM_FORMATO1_idx` (`FORMATO_ID` ASC) VISIBLE,
  INDEX `fk_item_subcategoria1_idx` (`subcategoria_ID_SUBCATEGORIA` ASC, `subcategoria_CATEGORIA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ITEM_COLOR1`
    FOREIGN KEY (`COLOR_ID`)
    REFERENCES `mydb`.`colores` (`COLOR_ID`),
  CONSTRAINT `fk_ITEM_CONDICION1`
    FOREIGN KEY (`CONDICION_ID`)
    REFERENCES `mydb`.`condiciones` (`CONDICION_ID`),
  CONSTRAINT `fk_ITEM_ESTADO_ITEM1`
    FOREIGN KEY (`ESTADO_ITEM_ID`)
    REFERENCES `mydb`.`estados_items` (`ESTADOITEM_ID`),
  CONSTRAINT `fk_ITEM_FORMATO1`
    FOREIGN KEY (`FORMATO_ID`)
    REFERENCES `mydb`.`formatos` (`FORMATO_ID`),
  CONSTRAINT `fk_item_subcategoria1`
    FOREIGN KEY (`subcategoria_ID_SUBCATEGORIA` , `subcategoria_CATEGORIA_ID`)
    REFERENCES `mydb`.`subcategorias` (`SUBCATEGORIA_ID` , `CATEGORIA_ID`),
  CONSTRAINT `fk_ITEM_TAMANO1`
    FOREIGN KEY (`TAMANO_ID`)
    REFERENCES `mydb`.`tamanos` (`TAMANO_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`estados_personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estados_personas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estados_personas` (
  `ESTADOPERSONA_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `FECHA_CREACION` DATETIME NOT NULL,
  `USUARIO_CREACION` VARCHAR(100) NOT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICACION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ESTADOPERSONA_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`roles_personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`roles_personas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`roles_personas` (
  `ROLPERSONA_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `FECHA_CREACION` DATETIME NOT NULL,
  `USUARIO_CREACION` VARCHAR(100) NOT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICACION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ROLPERSONA_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`personas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`personas` (
  `PERSONA_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRES` VARCHAR(100) NOT NULL,
  `PRIMER_APELLIDO` VARCHAR(100) NOT NULL,
  `SEGUNDO_APELLIDO` VARCHAR(100) NOT NULL,
  `CODIGO` VARCHAR(8) NOT NULL,
  `CORREO` VARCHAR(100) NOT NULL,
  `CONTRASENA` VARCHAR(45) NOT NULL,
  `ROL_PERSONA_ID_ROLPERSONA` INT NOT NULL,
  `ESTADO_PERSONA_ID_ESTADOPERSONA` INT NOT NULL,
  `FECHA_CREACION` DATETIME NOT NULL,
  `USUARIO_CREACION` INT NOT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICACION` INT NULL DEFAULT NULL,
  PRIMARY KEY (`PERSONA_ID`),
  INDEX `fk_PERSONA_ROL_PERSONA1_idx` (`ROL_PERSONA_ID_ROLPERSONA` ASC) VISIBLE,
  INDEX `fk_PERSONA_ESTADO_PERSONA1_idx` (`ESTADO_PERSONA_ID_ESTADOPERSONA` ASC) VISIBLE,
  CONSTRAINT `fk_PERSONA_ESTADO_PERSONA1`
    FOREIGN KEY (`ESTADO_PERSONA_ID_ESTADOPERSONA`)
    REFERENCES `mydb`.`estados_personas` (`ESTADOPERSONA_ID`),
  CONSTRAINT `fk_PERSONA_ROL_PERSONA1`
    FOREIGN KEY (`ROL_PERSONA_ID_ROLPERSONA`)
    REFERENCES `mydb`.`roles_personas` (`ROLPERSONA_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`alquileres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`alquileres` ;

CREATE TABLE IF NOT EXISTS `mydb`.`alquileres` (
  `PERSONA_ID` INT NOT NULL,
  `ITEM_ID` INT NOT NULL,
  `FECHA_INICIO` DATETIME NOT NULL,
  `FECHA_FIN` DATETIME NULL DEFAULT NULL,
  `MONTO` DECIMAL(10,2) NOT NULL,
  `FECHA_CREACION` DATETIME NOT NULL,
  `USUARIO_CREACION` INT NOT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICACION` INT NULL DEFAULT NULL,
  `ALQUILER_ID` INT NOT NULL AUTO_INCREMENT,
  `DEVUELTO` TINYINT NOT NULL,
  PRIMARY KEY (`ALQUILER_ID`),
  INDEX `fk_PERSONA_has_ITEM_ITEM1_idx` (`ITEM_ID` ASC) VISIBLE,
  INDEX `fk_PERSONA_has_ITEM_PERSONA1_idx` (`PERSONA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PERSONA_has_ITEM_ITEM1`
    FOREIGN KEY (`ITEM_ID`)
    REFERENCES `mydb`.`items` (`ITEM_ID`),
  CONSTRAINT `fk_PERSONA_has_ITEM_PERSONA1`
    FOREIGN KEY (`PERSONA_ID`)
    REFERENCES `mydb`.`personas` (`PERSONA_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`estados_chats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estados_chats` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estados_chats` (
  `ESTADOCHAT_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `FECHA_CREACION` DATETIME NOT NULL,
  `USUARIO_CREACION` VARCHAR(100) NOT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICACION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ESTADOCHAT_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`chats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`chats` ;

CREATE TABLE IF NOT EXISTS `mydb`.`chats` (
  `CHAT_ID` INT NOT NULL AUTO_INCREMENT,
  `FECHA_CREACION` DATETIME NOT NULL,
  `estado_chat_ID_ESTADOCHAT` INT NOT NULL,
  `USUARIO_CREACION` INT NOT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICACION` INT NULL DEFAULT NULL,
  PRIMARY KEY (`CHAT_ID`),
  INDEX `fk_CHAT_estado_chat1_idx` (`estado_chat_ID_ESTADOCHAT` ASC) VISIBLE,
  CONSTRAINT `fk_CHAT_estado_chat1`
    FOREIGN KEY (`estado_chat_ID_ESTADOCHAT`)
    REFERENCES `mydb`.`estados_chats` (`ESTADOCHAT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`formas_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`formas_pago` ;

CREATE TABLE IF NOT EXISTS `mydb`.`formas_pago` (
  `FORMAPAGO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `FECHA_CREACION` DATETIME NOT NULL,
  `USUARIO_CREACION` VARCHAR(100) NOT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICACION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`FORMAPAGO_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`monedas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`monedas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`monedas` (
  `MONEDA_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `FECHA_CREACION` DATETIME NOT NULL,
  `USUARIO_CREACION` VARCHAR(100) NOT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICACION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`MONEDA_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`comprobantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comprobantes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comprobantes` (
  `COMPROBANTE_ID` INT NOT NULL AUTO_INCREMENT,
  `MONTO` DECIMAL(10,2) NOT NULL,
  `TRANSACCION_ID` VARCHAR(45) NOT NULL,
  `FECHA_EMISION` DATETIME NOT NULL,
  `PERSONA_ID_PERSONA` INT NOT NULL,
  `FORMA_PAGO_ID_FORMAPAGO` INT NOT NULL,
  `MONEDA_ID_MONEDA` INT NOT NULL,
  `IMPUESTO` DECIMAL(10,2) NULL DEFAULT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICIACION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`COMPROBANTE_ID`),
  INDEX `fk_COMPROBANTE_PERSONA1_idx` (`PERSONA_ID_PERSONA` ASC) VISIBLE,
  INDEX `fk_COMPROBANTE_FORMA_PAGO1_idx` (`FORMA_PAGO_ID_FORMAPAGO` ASC) VISIBLE,
  INDEX `fk_COMPROBANTE_MONEDA1_idx` (`MONEDA_ID_MONEDA` ASC) VISIBLE,
  CONSTRAINT `fk_COMPROBANTE_FORMA_PAGO1`
    FOREIGN KEY (`FORMA_PAGO_ID_FORMAPAGO`)
    REFERENCES `mydb`.`formas_pago` (`FORMAPAGO_ID`),
  CONSTRAINT `fk_COMPROBANTE_MONEDA1`
    FOREIGN KEY (`MONEDA_ID_MONEDA`)
    REFERENCES `mydb`.`monedas` (`MONEDA_ID`),
  CONSTRAINT `fk_COMPROBANTE_PERSONA1`
    FOREIGN KEY (`PERSONA_ID_PERSONA`)
    REFERENCES `mydb`.`personas` (`PERSONA_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`detalles_comprobantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`detalles_comprobantes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`detalles_comprobantes` (
  `DETALLECOM_ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(100) NOT NULL,
  `PRECIO` DECIMAL(10,2) NOT NULL,
  `ITEM_ID_ITEM` INT NULL DEFAULT NULL,
  `ALQUILER_ID_ALQUILER` INT NULL DEFAULT NULL,
  `COMPROBANTE_ID_COMPROBANTE` INT NOT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICACION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`DETALLECOM_ID`, `COMPROBANTE_ID_COMPROBANTE`),
  INDEX `fk_DETALLE_COMPROBANTE_ITEM1_idx` (`ITEM_ID_ITEM` ASC) VISIBLE,
  INDEX `fk_DETALLE_COMPROBANTE_ALQUILER1_idx` (`ALQUILER_ID_ALQUILER` ASC) VISIBLE,
  INDEX `fk_DETALLE_COMPROBANTE_COMPROBANTE1_idx` (`COMPROBANTE_ID_COMPROBANTE` ASC) VISIBLE,
  CONSTRAINT `fk_DETALLE_COMPROBANTE_ALQUILER1`
    FOREIGN KEY (`ALQUILER_ID_ALQUILER`)
    REFERENCES `mydb`.`alquileres` (`ALQUILER_ID`),
  CONSTRAINT `fk_DETALLE_COMPROBANTE_COMPROBANTE1`
    FOREIGN KEY (`COMPROBANTE_ID_COMPROBANTE`)
    REFERENCES `mydb`.`comprobantes` (`COMPROBANTE_ID`),
  CONSTRAINT `fk_DETALLE_COMPROBANTE_ITEM1`
    FOREIGN KEY (`ITEM_ID_ITEM`)
    REFERENCES `mydb`.`items` (`ITEM_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`estados_mensajes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estados_mensajes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estados_mensajes` (
  `ESTADOMSJ_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(100) NOT NULL,
  `FECHA_CREACION` DATETIME NOT NULL,
  `USUARIO_CREACION` VARCHAR(100) NOT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICACION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ESTADOMSJ_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`estados_publicaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estados_publicaciones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estados_publicaciones` (
  `ESTADOPUBLI_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(100) NOT NULL,
  `FECHA_CREACION` DATETIME NOT NULL,
  `USUARIO_CREACION` VARCHAR(100) NOT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICACION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ESTADOPUBLI_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`publicaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`publicaciones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`publicaciones` (
  `PUBLICACION_ID` INT NOT NULL AUTO_INCREMENT,
  `FECHA_ALTA` DATETIME NOT NULL,
  `FECHA_BAJA` DATETIME NULL DEFAULT NULL,
  `ESTADO_PUBLICACION_ID` INT NOT NULL,
  `ITEM_ID_ITEM` INT NOT NULL,
  `PERSONA_ID` INT NOT NULL,
  `CALIFICACION` INT NULL DEFAULT '0',
  PRIMARY KEY (`PUBLICACION_ID`),
  INDEX `fk_PUBLICACION_ESTADO_PUBLICACION1_idx` (`ESTADO_PUBLICACION_ID` ASC) VISIBLE,
  INDEX `fk_PUBLICACION_ITEM1_idx` (`ITEM_ID_ITEM` ASC) VISIBLE,
  INDEX `fk_PUBLICACION_PERSONA1_idx` (`PERSONA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PUBLICACION_ESTADO_PUBLICACION1`
    FOREIGN KEY (`ESTADO_PUBLICACION_ID`)
    REFERENCES `mydb`.`estados_publicaciones` (`ESTADOPUBLI_ID`),
  CONSTRAINT `fk_PUBLICACION_ITEM1`
    FOREIGN KEY (`ITEM_ID_ITEM`)
    REFERENCES `mydb`.`items` (`ITEM_ID`),
  CONSTRAINT `fk_PUBLICACION_PERSONA1`
    FOREIGN KEY (`PERSONA_ID`)
    REFERENCES `mydb`.`personas` (`PERSONA_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`historias_publicaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`historias_publicaciones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`historias_publicaciones` (
  `HISTORIAPUBLI_ID` INT NOT NULL AUTO_INCREMENT,
  `FECHA_MODIFICACION` DATETIME NOT NULL,
  `PUBLICACION_ID` INT NOT NULL,
  `USUARIO_MODIFICACION` INT NOT NULL,
  PRIMARY KEY (`HISTORIAPUBLI_ID`, `PUBLICACION_ID`),
  INDEX `fk_HISTORIA_PUBLI_PUBLICACION1_idx` (`PUBLICACION_ID` ASC) VISIBLE,
  CONSTRAINT `fk_HISTORIA_PUBLI_PUBLICACION1`
    FOREIGN KEY (`PUBLICACION_ID`)
    REFERENCES `mydb`.`publicaciones` (`PUBLICACION_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`motivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`motivos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`motivos` (
  `MOTIVO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NULL DEFAULT NULL,
  `FECHA_CREACION` DATETIME NOT NULL,
  `USUARIO_CREACION` VARCHAR(100) NOT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICACION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`MOTIVO_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`notificaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`notificaciones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`notificaciones` (
  `NOTIFICACION_ID` INT NOT NULL AUTO_INCREMENT,
  `FECHA` DATETIME NOT NULL,
  `MENSAJE` VARCHAR(255) NOT NULL,
  `PERSONA_ID` INT NOT NULL,
  `MOTIVO_ID_MOTIVO` INT NOT NULL,
  PRIMARY KEY (`NOTIFICACION_ID`),
  INDEX `fk_NOTIFIFACION_PERSONA1_idx` (`PERSONA_ID` ASC) VISIBLE,
  INDEX `fk_notificacion_MOTIVO1_idx` (`MOTIVO_ID_MOTIVO` ASC) VISIBLE,
  CONSTRAINT `fk_notificacion_MOTIVO1`
    FOREIGN KEY (`MOTIVO_ID_MOTIVO`)
    REFERENCES `mydb`.`motivos` (`MOTIVO_ID`),
  CONSTRAINT `fk_NOTIFIFACION_PERSONA1`
    FOREIGN KEY (`PERSONA_ID`)
    REFERENCES `mydb`.`personas` (`PERSONA_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`incidencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`incidencias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`incidencias` (
  `INCIDENCIA_ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(45) NOT NULL,
  `FECHA_CREACION` DATETIME NOT NULL,
  `FECHA_SOLUCION` DATETIME NULL DEFAULT NULL,
  `NOTIFIFACION_ID` INT NOT NULL,
  `PERSONA_ID` INT NOT NULL,
  `MOTIVO_ID_MOTIVO` INT NOT NULL,
  `USUARIO_CREACION` INT NOT NULL,
  `USUARIO_SOLUCION` INT NULL DEFAULT NULL,
  `FECHA_MODIFICACION` DATETIME NULL DEFAULT NULL,
  `USUARIO_MODIFICACION` INT NULL DEFAULT NULL,
  `RESUELTO` TINYINT NULL DEFAULT '0',
  PRIMARY KEY (`INCIDENCIA_ID`),
  INDEX `fk_INCIDENCIA_NOTIFIFACION1_idx` (`NOTIFIFACION_ID` ASC) VISIBLE,
  INDEX `fk_INCIDENCIA_PERSONA1_idx` (`PERSONA_ID` ASC) VISIBLE,
  INDEX `fk_INCIDENCIA_MOTIVO1_idx` (`MOTIVO_ID_MOTIVO` ASC) VISIBLE,
  CONSTRAINT `fk_INCIDENCIA_MOTIVO1`
    FOREIGN KEY (`MOTIVO_ID_MOTIVO`)
    REFERENCES `mydb`.`motivos` (`MOTIVO_ID`),
  CONSTRAINT `fk_INCIDENCIA_NOTIFIFACION1`
    FOREIGN KEY (`NOTIFIFACION_ID`)
    REFERENCES `mydb`.`notificaciones` (`NOTIFICACION_ID`),
  CONSTRAINT `fk_INCIDENCIA_PERSONA1`
    FOREIGN KEY (`PERSONA_ID`)
    REFERENCES `mydb`.`personas` (`PERSONA_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`mensajes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`mensajes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`mensajes` (
  `MENSAJE_ID` INT NOT NULL AUTO_INCREMENT,
  `CHAT_ID_CHAT` INT NOT NULL,
  `FECHA_ENVIO` DATETIME NOT NULL,
  `FECHA_LEIDO` DATETIME NULL DEFAULT NULL,
  `MENSAJE` TEXT NOT NULL,
  `ESTADO_MSJ_ID` INT NOT NULL,
  `PERSONA_ID` INT NOT NULL,
  PRIMARY KEY (`MENSAJE_ID`, `CHAT_ID_CHAT`),
  INDEX `fk_MENSAJE_CHAT1_idx` (`CHAT_ID_CHAT` ASC) VISIBLE,
  INDEX `fk_MENSAJE_PERSONA1_idx` (`PERSONA_ID` ASC) VISIBLE,
  INDEX `fk_MENSAJE_ESTADO_MSJ1_idx` (`ESTADO_MSJ_ID` ASC) VISIBLE,
  CONSTRAINT `fk_MENSAJE_CHAT1`
    FOREIGN KEY (`CHAT_ID_CHAT`)
    REFERENCES `mydb`.`chats` (`CHAT_ID`),
  CONSTRAINT `fk_MENSAJE_ESTADO_MSJ1`
    FOREIGN KEY (`ESTADO_MSJ_ID`)
    REFERENCES `mydb`.`estados_mensajes` (`ESTADOMSJ_ID`),
  CONSTRAINT `fk_MENSAJE_PERSONA1`
    FOREIGN KEY (`PERSONA_ID`)
    REFERENCES `mydb`.`personas` (`PERSONA_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`personas_chats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`personas_chats` ;

CREATE TABLE IF NOT EXISTS `mydb`.`personas_chats` (
  `PERSONA_ID` INT NOT NULL,
  `CHAT_ID` INT NOT NULL,
  `ULTIMA_ACTIVIDAD` DATETIME NOT NULL,
  PRIMARY KEY (`PERSONA_ID`, `CHAT_ID`),
  INDEX `fk_PERSONA_has_CHAT_CHAT1_idx` (`CHAT_ID` ASC) VISIBLE,
  INDEX `fk_PERSONA_has_CHAT_PERSONA1_idx` (`PERSONA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PERSONA_has_CHAT_CHAT1`
    FOREIGN KEY (`CHAT_ID`)
    REFERENCES `mydb`.`chats` (`CHAT_ID`),
  CONSTRAINT `fk_PERSONA_has_CHAT_PERSONA1`
    FOREIGN KEY (`PERSONA_ID`)
    REFERENCES `mydb`.`personas` (`PERSONA_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`personas_pucp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`personas_pucp` ;

CREATE TABLE IF NOT EXISTS `mydb`.`personas_pucp` (
  `PERSONASPUCP_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRES` VARCHAR(100) NOT NULL,
  `PRIMER_APELLIDO` VARCHAR(100) NOT NULL,
  `SEGUNDO_APELLIDO` VARCHAR(100) NOT NULL,
  `CODIGO` VARCHAR(8) NOT NULL,
  `CORREO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`PERSONASPUCP_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`tarjetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tarjetas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tarjetas` (
  `TARJETAS_ID` INT NOT NULL AUTO_INCREMENT,
  `NUMERO` VARCHAR(16) NOT NULL,
  `CCV` VARCHAR(3) NOT NULL,
  `FECHA_VENCIMIENTO` DATETIME NOT NULL,
  PRIMARY KEY (`TARJETAS_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`yape`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`yape` ;

CREATE TABLE IF NOT EXISTS `mydb`.`yape` (
  `YAPE_ID` INT NOT NULL AUTO_INCREMENT,
  `NUMERO` VARCHAR(9) NOT NULL,
  `CODIGO_APROBACION` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`YAPE_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
