//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SquirlearnWA.incidenciaSOAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", ConfigurationName="incidenciaSOAP.Incidencia")]
    public interface Incidencia {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://inciNoti.squirlearnws.mycompany.com/Incidencia/insertarIncidenciaRequest", ReplyAction="http://inciNoti.squirlearnws.mycompany.com/Incidencia/insertarIncidenciaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SquirlearnWA.incidenciaSOAP.insertarIncidenciaResponse insertarIncidencia(SquirlearnWA.incidenciaSOAP.insertarIncidenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inciNoti.squirlearnws.mycompany.com/Incidencia/insertarIncidenciaRequest", ReplyAction="http://inciNoti.squirlearnws.mycompany.com/Incidencia/insertarIncidenciaResponse")]
        System.Threading.Tasks.Task<SquirlearnWA.incidenciaSOAP.insertarIncidenciaResponse> insertarIncidenciaAsync(SquirlearnWA.incidenciaSOAP.insertarIncidenciaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://inciNoti.squirlearnws.mycompany.com/Incidencia/listarPorResolucionIncidenc" +
            "iaRequest", ReplyAction="http://inciNoti.squirlearnws.mycompany.com/Incidencia/listarPorResolucionIncidenc" +
            "iaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SquirlearnWA.incidenciaSOAP.listarPorResolucionIncidenciaResponse listarPorResolucionIncidencia(SquirlearnWA.incidenciaSOAP.listarPorResolucionIncidenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inciNoti.squirlearnws.mycompany.com/Incidencia/listarPorResolucionIncidenc" +
            "iaRequest", ReplyAction="http://inciNoti.squirlearnws.mycompany.com/Incidencia/listarPorResolucionIncidenc" +
            "iaResponse")]
        System.Threading.Tasks.Task<SquirlearnWA.incidenciaSOAP.listarPorResolucionIncidenciaResponse> listarPorResolucionIncidenciaAsync(SquirlearnWA.incidenciaSOAP.listarPorResolucionIncidenciaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://inciNoti.squirlearnws.mycompany.com/Incidencia/listarTodasIncidenciasReque" +
            "st", ReplyAction="http://inciNoti.squirlearnws.mycompany.com/Incidencia/listarTodasIncidenciasRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SquirlearnWA.incidenciaSOAP.listarTodasIncidenciasResponse listarTodasIncidencias(SquirlearnWA.incidenciaSOAP.listarTodasIncidenciasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inciNoti.squirlearnws.mycompany.com/Incidencia/listarTodasIncidenciasReque" +
            "st", ReplyAction="http://inciNoti.squirlearnws.mycompany.com/Incidencia/listarTodasIncidenciasRespo" +
            "nse")]
        System.Threading.Tasks.Task<SquirlearnWA.incidenciaSOAP.listarTodasIncidenciasResponse> listarTodasIncidenciasAsync(SquirlearnWA.incidenciaSOAP.listarTodasIncidenciasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://inciNoti.squirlearnws.mycompany.com/Incidencia/obtenerPorIdIncidenciaReque" +
            "st", ReplyAction="http://inciNoti.squirlearnws.mycompany.com/Incidencia/obtenerPorIdIncidenciaRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SquirlearnWA.incidenciaSOAP.obtenerPorIdIncidenciaResponse obtenerPorIdIncidencia(SquirlearnWA.incidenciaSOAP.obtenerPorIdIncidenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inciNoti.squirlearnws.mycompany.com/Incidencia/obtenerPorIdIncidenciaReque" +
            "st", ReplyAction="http://inciNoti.squirlearnws.mycompany.com/Incidencia/obtenerPorIdIncidenciaRespo" +
            "nse")]
        System.Threading.Tasks.Task<SquirlearnWA.incidenciaSOAP.obtenerPorIdIncidenciaResponse> obtenerPorIdIncidenciaAsync(SquirlearnWA.incidenciaSOAP.obtenerPorIdIncidenciaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://inciNoti.squirlearnws.mycompany.com/Incidencia/modificarIncidenciaRequest", ReplyAction="http://inciNoti.squirlearnws.mycompany.com/Incidencia/modificarIncidenciaResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SquirlearnWA.incidenciaSOAP.modificarIncidenciaResponse modificarIncidencia(SquirlearnWA.incidenciaSOAP.modificarIncidenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inciNoti.squirlearnws.mycompany.com/Incidencia/modificarIncidenciaRequest", ReplyAction="http://inciNoti.squirlearnws.mycompany.com/Incidencia/modificarIncidenciaResponse" +
            "")]
        System.Threading.Tasks.Task<SquirlearnWA.incidenciaSOAP.modificarIncidenciaResponse> modificarIncidenciaAsync(SquirlearnWA.incidenciaSOAP.modificarIncidenciaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarIncidencia", WrapperNamespace="http://inciNoti.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class insertarIncidenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int notificacionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int personaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int motivoId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int usuarioSolucion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuarioCreacion;
        
        public insertarIncidenciaRequest() {
        }
        
        public insertarIncidenciaRequest(string descripcion, int notificacionId, int personaId, int motivoId, int usuarioSolucion, string usuarioCreacion) {
            this.descripcion = descripcion;
            this.notificacionId = notificacionId;
            this.personaId = personaId;
            this.motivoId = motivoId;
            this.usuarioSolucion = usuarioSolucion;
            this.usuarioCreacion = usuarioCreacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarIncidenciaResponse", WrapperNamespace="http://inciNoti.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class insertarIncidenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarIncidenciaResponse() {
        }
        
        public insertarIncidenciaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/")]
    public partial class incidenciaDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int incidenciaIdField;
        
        private bool incidenciaIdFieldSpecified;
        
        private motivoDto motivoField;
        
        private notificacionDto notificacionField;
        
        private personaDto personaField;
        
        private int resueltoField;
        
        private bool resueltoFieldSpecified;
        
        private string usuarioCreacionField;
        
        private int usuarioSolucionField;
        
        private bool usuarioSolucionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int incidenciaId {
            get {
                return this.incidenciaIdField;
            }
            set {
                this.incidenciaIdField = value;
                this.RaisePropertyChanged("incidenciaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool incidenciaIdSpecified {
            get {
                return this.incidenciaIdFieldSpecified;
            }
            set {
                this.incidenciaIdFieldSpecified = value;
                this.RaisePropertyChanged("incidenciaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public motivoDto motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
                this.RaisePropertyChanged("motivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public notificacionDto notificacion {
            get {
                return this.notificacionField;
            }
            set {
                this.notificacionField = value;
                this.RaisePropertyChanged("notificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public personaDto persona {
            get {
                return this.personaField;
            }
            set {
                this.personaField = value;
                this.RaisePropertyChanged("persona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int resuelto {
            get {
                return this.resueltoField;
            }
            set {
                this.resueltoField = value;
                this.RaisePropertyChanged("resuelto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resueltoSpecified {
            get {
                return this.resueltoFieldSpecified;
            }
            set {
                this.resueltoFieldSpecified = value;
                this.RaisePropertyChanged("resueltoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string usuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("usuarioCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int usuarioSolucion {
            get {
                return this.usuarioSolucionField;
            }
            set {
                this.usuarioSolucionField = value;
                this.RaisePropertyChanged("usuarioSolucion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usuarioSolucionSpecified {
            get {
                return this.usuarioSolucionFieldSpecified;
            }
            set {
                this.usuarioSolucionFieldSpecified = value;
                this.RaisePropertyChanged("usuarioSolucionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/")]
    public partial class motivoDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int motivoIdField;
        
        private bool motivoIdFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int motivoId {
            get {
                return this.motivoIdField;
            }
            set {
                this.motivoIdField = value;
                this.RaisePropertyChanged("motivoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool motivoIdSpecified {
            get {
                return this.motivoIdFieldSpecified;
            }
            set {
                this.motivoIdFieldSpecified = value;
                this.RaisePropertyChanged("motivoIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/")]
    public partial class rolPersonaDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private int rolPersonaIdField;
        
        private bool rolPersonaIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int rolPersonaId {
            get {
                return this.rolPersonaIdField;
            }
            set {
                this.rolPersonaIdField = value;
                this.RaisePropertyChanged("rolPersonaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rolPersonaIdSpecified {
            get {
                return this.rolPersonaIdFieldSpecified;
            }
            set {
                this.rolPersonaIdFieldSpecified = value;
                this.RaisePropertyChanged("rolPersonaIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/")]
    public partial class estadoPersonaDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int estadoPersonaIdField;
        
        private bool estadoPersonaIdFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int estadoPersonaId {
            get {
                return this.estadoPersonaIdField;
            }
            set {
                this.estadoPersonaIdField = value;
                this.RaisePropertyChanged("estadoPersonaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoPersonaIdSpecified {
            get {
                return this.estadoPersonaIdFieldSpecified;
            }
            set {
                this.estadoPersonaIdFieldSpecified = value;
                this.RaisePropertyChanged("estadoPersonaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/")]
    public partial class personaDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string contrasenaField;
        
        private string correoField;
        
        private estadoPersonaDto estadoPersonaField;
        
        private string nombresField;
        
        private int personaIdField;
        
        private bool personaIdFieldSpecified;
        
        private string primerApellidoField;
        
        private rolPersonaDto[] rolPersonaField;
        
        private string segundoApellidoField;
        
        private string ultimaActividadField;
        
        private string usuarioCreacionField;
        
        private string usuarioModificacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("contrasena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public estadoPersonaDto estadoPersona {
            get {
                return this.estadoPersonaField;
            }
            set {
                this.estadoPersonaField = value;
                this.RaisePropertyChanged("estadoPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int personaId {
            get {
                return this.personaIdField;
            }
            set {
                this.personaIdField = value;
                this.RaisePropertyChanged("personaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool personaIdSpecified {
            get {
                return this.personaIdFieldSpecified;
            }
            set {
                this.personaIdFieldSpecified = value;
                this.RaisePropertyChanged("personaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
                this.RaisePropertyChanged("primerApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rolPersona", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public rolPersonaDto[] rolPersona {
            get {
                return this.rolPersonaField;
            }
            set {
                this.rolPersonaField = value;
                this.RaisePropertyChanged("rolPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
                this.RaisePropertyChanged("segundoApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ultimaActividad {
            get {
                return this.ultimaActividadField;
            }
            set {
                this.ultimaActividadField = value;
                this.RaisePropertyChanged("ultimaActividad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string usuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("usuarioCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string usuarioModificacion {
            get {
                return this.usuarioModificacionField;
            }
            set {
                this.usuarioModificacionField = value;
                this.RaisePropertyChanged("usuarioModificacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/")]
    public partial class notificacionDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaField;
        
        private string mensajeField;
        
        private int notificacionIdField;
        
        private bool notificacionIdFieldSpecified;
        
        private personaDto personaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int notificacionId {
            get {
                return this.notificacionIdField;
            }
            set {
                this.notificacionIdField = value;
                this.RaisePropertyChanged("notificacionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool notificacionIdSpecified {
            get {
                return this.notificacionIdFieldSpecified;
            }
            set {
                this.notificacionIdFieldSpecified = value;
                this.RaisePropertyChanged("notificacionIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public personaDto persona {
            get {
                return this.personaField;
            }
            set {
                this.personaField = value;
                this.RaisePropertyChanged("persona");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorResolucionIncidencia", WrapperNamespace="http://inciNoti.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class listarPorResolucionIncidenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool resuelto;
        
        public listarPorResolucionIncidenciaRequest() {
        }
        
        public listarPorResolucionIncidenciaRequest(bool resuelto) {
            this.resuelto = resuelto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorResolucionIncidenciaResponse", WrapperNamespace="http://inciNoti.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class listarPorResolucionIncidenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SquirlearnWA.incidenciaSOAP.incidenciaDto[] @return;
        
        public listarPorResolucionIncidenciaResponse() {
        }
        
        public listarPorResolucionIncidenciaResponse(SquirlearnWA.incidenciaSOAP.incidenciaDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasIncidencias", WrapperNamespace="http://inciNoti.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class listarTodasIncidenciasRequest {
        
        public listarTodasIncidenciasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasIncidenciasResponse", WrapperNamespace="http://inciNoti.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class listarTodasIncidenciasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SquirlearnWA.incidenciaSOAP.incidenciaDto[] @return;
        
        public listarTodasIncidenciasResponse() {
        }
        
        public listarTodasIncidenciasResponse(SquirlearnWA.incidenciaSOAP.incidenciaDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdIncidencia", WrapperNamespace="http://inciNoti.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class obtenerPorIdIncidenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerPorIdIncidenciaRequest() {
        }
        
        public obtenerPorIdIncidenciaRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdIncidenciaResponse", WrapperNamespace="http://inciNoti.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class obtenerPorIdIncidenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SquirlearnWA.incidenciaSOAP.incidenciaDto @return;
        
        public obtenerPorIdIncidenciaResponse() {
        }
        
        public obtenerPorIdIncidenciaResponse(SquirlearnWA.incidenciaSOAP.incidenciaDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarIncidencia", WrapperNamespace="http://inciNoti.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class modificarIncidenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int notificacionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int personaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int motivoId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int resuelto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int solucionadorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuarioCreacion;
        
        public modificarIncidenciaRequest() {
        }
        
        public modificarIncidenciaRequest(int id, string descripcion, int notificacionId, int personaId, int motivoId, int resuelto, int solucionadorId, string usuarioCreacion) {
            this.id = id;
            this.descripcion = descripcion;
            this.notificacionId = notificacionId;
            this.personaId = personaId;
            this.motivoId = motivoId;
            this.resuelto = resuelto;
            this.solucionadorId = solucionadorId;
            this.usuarioCreacion = usuarioCreacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarIncidenciaResponse", WrapperNamespace="http://inciNoti.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class modificarIncidenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarIncidenciaResponse() {
        }
        
        public modificarIncidenciaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IncidenciaChannel : SquirlearnWA.incidenciaSOAP.Incidencia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IncidenciaClient : System.ServiceModel.ClientBase<SquirlearnWA.incidenciaSOAP.Incidencia>, SquirlearnWA.incidenciaSOAP.Incidencia {
        
        public IncidenciaClient() {
        }
        
        public IncidenciaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IncidenciaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IncidenciaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IncidenciaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SquirlearnWA.incidenciaSOAP.insertarIncidenciaResponse SquirlearnWA.incidenciaSOAP.Incidencia.insertarIncidencia(SquirlearnWA.incidenciaSOAP.insertarIncidenciaRequest request) {
            return base.Channel.insertarIncidencia(request);
        }
        
        public int insertarIncidencia(string descripcion, int notificacionId, int personaId, int motivoId, int usuarioSolucion, string usuarioCreacion) {
            SquirlearnWA.incidenciaSOAP.insertarIncidenciaRequest inValue = new SquirlearnWA.incidenciaSOAP.insertarIncidenciaRequest();
            inValue.descripcion = descripcion;
            inValue.notificacionId = notificacionId;
            inValue.personaId = personaId;
            inValue.motivoId = motivoId;
            inValue.usuarioSolucion = usuarioSolucion;
            inValue.usuarioCreacion = usuarioCreacion;
            SquirlearnWA.incidenciaSOAP.insertarIncidenciaResponse retVal = ((SquirlearnWA.incidenciaSOAP.Incidencia)(this)).insertarIncidencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SquirlearnWA.incidenciaSOAP.insertarIncidenciaResponse> SquirlearnWA.incidenciaSOAP.Incidencia.insertarIncidenciaAsync(SquirlearnWA.incidenciaSOAP.insertarIncidenciaRequest request) {
            return base.Channel.insertarIncidenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SquirlearnWA.incidenciaSOAP.insertarIncidenciaResponse> insertarIncidenciaAsync(string descripcion, int notificacionId, int personaId, int motivoId, int usuarioSolucion, string usuarioCreacion) {
            SquirlearnWA.incidenciaSOAP.insertarIncidenciaRequest inValue = new SquirlearnWA.incidenciaSOAP.insertarIncidenciaRequest();
            inValue.descripcion = descripcion;
            inValue.notificacionId = notificacionId;
            inValue.personaId = personaId;
            inValue.motivoId = motivoId;
            inValue.usuarioSolucion = usuarioSolucion;
            inValue.usuarioCreacion = usuarioCreacion;
            return ((SquirlearnWA.incidenciaSOAP.Incidencia)(this)).insertarIncidenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SquirlearnWA.incidenciaSOAP.listarPorResolucionIncidenciaResponse SquirlearnWA.incidenciaSOAP.Incidencia.listarPorResolucionIncidencia(SquirlearnWA.incidenciaSOAP.listarPorResolucionIncidenciaRequest request) {
            return base.Channel.listarPorResolucionIncidencia(request);
        }
        
        public SquirlearnWA.incidenciaSOAP.incidenciaDto[] listarPorResolucionIncidencia(bool resuelto) {
            SquirlearnWA.incidenciaSOAP.listarPorResolucionIncidenciaRequest inValue = new SquirlearnWA.incidenciaSOAP.listarPorResolucionIncidenciaRequest();
            inValue.resuelto = resuelto;
            SquirlearnWA.incidenciaSOAP.listarPorResolucionIncidenciaResponse retVal = ((SquirlearnWA.incidenciaSOAP.Incidencia)(this)).listarPorResolucionIncidencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SquirlearnWA.incidenciaSOAP.listarPorResolucionIncidenciaResponse> SquirlearnWA.incidenciaSOAP.Incidencia.listarPorResolucionIncidenciaAsync(SquirlearnWA.incidenciaSOAP.listarPorResolucionIncidenciaRequest request) {
            return base.Channel.listarPorResolucionIncidenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SquirlearnWA.incidenciaSOAP.listarPorResolucionIncidenciaResponse> listarPorResolucionIncidenciaAsync(bool resuelto) {
            SquirlearnWA.incidenciaSOAP.listarPorResolucionIncidenciaRequest inValue = new SquirlearnWA.incidenciaSOAP.listarPorResolucionIncidenciaRequest();
            inValue.resuelto = resuelto;
            return ((SquirlearnWA.incidenciaSOAP.Incidencia)(this)).listarPorResolucionIncidenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SquirlearnWA.incidenciaSOAP.listarTodasIncidenciasResponse SquirlearnWA.incidenciaSOAP.Incidencia.listarTodasIncidencias(SquirlearnWA.incidenciaSOAP.listarTodasIncidenciasRequest request) {
            return base.Channel.listarTodasIncidencias(request);
        }
        
        public SquirlearnWA.incidenciaSOAP.incidenciaDto[] listarTodasIncidencias() {
            SquirlearnWA.incidenciaSOAP.listarTodasIncidenciasRequest inValue = new SquirlearnWA.incidenciaSOAP.listarTodasIncidenciasRequest();
            SquirlearnWA.incidenciaSOAP.listarTodasIncidenciasResponse retVal = ((SquirlearnWA.incidenciaSOAP.Incidencia)(this)).listarTodasIncidencias(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SquirlearnWA.incidenciaSOAP.listarTodasIncidenciasResponse> SquirlearnWA.incidenciaSOAP.Incidencia.listarTodasIncidenciasAsync(SquirlearnWA.incidenciaSOAP.listarTodasIncidenciasRequest request) {
            return base.Channel.listarTodasIncidenciasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SquirlearnWA.incidenciaSOAP.listarTodasIncidenciasResponse> listarTodasIncidenciasAsync() {
            SquirlearnWA.incidenciaSOAP.listarTodasIncidenciasRequest inValue = new SquirlearnWA.incidenciaSOAP.listarTodasIncidenciasRequest();
            return ((SquirlearnWA.incidenciaSOAP.Incidencia)(this)).listarTodasIncidenciasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SquirlearnWA.incidenciaSOAP.obtenerPorIdIncidenciaResponse SquirlearnWA.incidenciaSOAP.Incidencia.obtenerPorIdIncidencia(SquirlearnWA.incidenciaSOAP.obtenerPorIdIncidenciaRequest request) {
            return base.Channel.obtenerPorIdIncidencia(request);
        }
        
        public SquirlearnWA.incidenciaSOAP.incidenciaDto obtenerPorIdIncidencia(int id) {
            SquirlearnWA.incidenciaSOAP.obtenerPorIdIncidenciaRequest inValue = new SquirlearnWA.incidenciaSOAP.obtenerPorIdIncidenciaRequest();
            inValue.id = id;
            SquirlearnWA.incidenciaSOAP.obtenerPorIdIncidenciaResponse retVal = ((SquirlearnWA.incidenciaSOAP.Incidencia)(this)).obtenerPorIdIncidencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SquirlearnWA.incidenciaSOAP.obtenerPorIdIncidenciaResponse> SquirlearnWA.incidenciaSOAP.Incidencia.obtenerPorIdIncidenciaAsync(SquirlearnWA.incidenciaSOAP.obtenerPorIdIncidenciaRequest request) {
            return base.Channel.obtenerPorIdIncidenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SquirlearnWA.incidenciaSOAP.obtenerPorIdIncidenciaResponse> obtenerPorIdIncidenciaAsync(int id) {
            SquirlearnWA.incidenciaSOAP.obtenerPorIdIncidenciaRequest inValue = new SquirlearnWA.incidenciaSOAP.obtenerPorIdIncidenciaRequest();
            inValue.id = id;
            return ((SquirlearnWA.incidenciaSOAP.Incidencia)(this)).obtenerPorIdIncidenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SquirlearnWA.incidenciaSOAP.modificarIncidenciaResponse SquirlearnWA.incidenciaSOAP.Incidencia.modificarIncidencia(SquirlearnWA.incidenciaSOAP.modificarIncidenciaRequest request) {
            return base.Channel.modificarIncidencia(request);
        }
        
        public int modificarIncidencia(int id, string descripcion, int notificacionId, int personaId, int motivoId, int resuelto, int solucionadorId, string usuarioCreacion) {
            SquirlearnWA.incidenciaSOAP.modificarIncidenciaRequest inValue = new SquirlearnWA.incidenciaSOAP.modificarIncidenciaRequest();
            inValue.id = id;
            inValue.descripcion = descripcion;
            inValue.notificacionId = notificacionId;
            inValue.personaId = personaId;
            inValue.motivoId = motivoId;
            inValue.resuelto = resuelto;
            inValue.solucionadorId = solucionadorId;
            inValue.usuarioCreacion = usuarioCreacion;
            SquirlearnWA.incidenciaSOAP.modificarIncidenciaResponse retVal = ((SquirlearnWA.incidenciaSOAP.Incidencia)(this)).modificarIncidencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SquirlearnWA.incidenciaSOAP.modificarIncidenciaResponse> SquirlearnWA.incidenciaSOAP.Incidencia.modificarIncidenciaAsync(SquirlearnWA.incidenciaSOAP.modificarIncidenciaRequest request) {
            return base.Channel.modificarIncidenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SquirlearnWA.incidenciaSOAP.modificarIncidenciaResponse> modificarIncidenciaAsync(int id, string descripcion, int notificacionId, int personaId, int motivoId, int resuelto, int solucionadorId, string usuarioCreacion) {
            SquirlearnWA.incidenciaSOAP.modificarIncidenciaRequest inValue = new SquirlearnWA.incidenciaSOAP.modificarIncidenciaRequest();
            inValue.id = id;
            inValue.descripcion = descripcion;
            inValue.notificacionId = notificacionId;
            inValue.personaId = personaId;
            inValue.motivoId = motivoId;
            inValue.resuelto = resuelto;
            inValue.solucionadorId = solucionadorId;
            inValue.usuarioCreacion = usuarioCreacion;
            return ((SquirlearnWA.incidenciaSOAP.Incidencia)(this)).modificarIncidenciaAsync(inValue);
        }
    }
}
