//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SquirlearnWA.notificacionSOAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", ConfigurationName="notificacionSOAP.Notificacion")]
    public interface Notificacion {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://inciNoti.squirlearnws.mycompany.com/Notificacion/insertarNotificacionReque" +
            "st", ReplyAction="http://inciNoti.squirlearnws.mycompany.com/Notificacion/insertarNotificacionRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SquirlearnWA.notificacionSOAP.insertarNotificacionResponse insertarNotificacion(SquirlearnWA.notificacionSOAP.insertarNotificacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inciNoti.squirlearnws.mycompany.com/Notificacion/insertarNotificacionReque" +
            "st", ReplyAction="http://inciNoti.squirlearnws.mycompany.com/Notificacion/insertarNotificacionRespo" +
            "nse")]
        System.Threading.Tasks.Task<SquirlearnWA.notificacionSOAP.insertarNotificacionResponse> insertarNotificacionAsync(SquirlearnWA.notificacionSOAP.insertarNotificacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://inciNoti.squirlearnws.mycompany.com/Notificacion/obtenerPorIdNotificacionR" +
            "equest", ReplyAction="http://inciNoti.squirlearnws.mycompany.com/Notificacion/obtenerPorIdNotificacionR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SquirlearnWA.notificacionSOAP.obtenerPorIdNotificacionResponse obtenerPorIdNotificacion(SquirlearnWA.notificacionSOAP.obtenerPorIdNotificacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inciNoti.squirlearnws.mycompany.com/Notificacion/obtenerPorIdNotificacionR" +
            "equest", ReplyAction="http://inciNoti.squirlearnws.mycompany.com/Notificacion/obtenerPorIdNotificacionR" +
            "esponse")]
        System.Threading.Tasks.Task<SquirlearnWA.notificacionSOAP.obtenerPorIdNotificacionResponse> obtenerPorIdNotificacionAsync(SquirlearnWA.notificacionSOAP.obtenerPorIdNotificacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://inciNoti.squirlearnws.mycompany.com/Notificacion/listarPorPersonaNotificac" +
            "ionRequest", ReplyAction="http://inciNoti.squirlearnws.mycompany.com/Notificacion/listarPorPersonaNotificac" +
            "ionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SquirlearnWA.notificacionSOAP.listarPorPersonaNotificacionResponse listarPorPersonaNotificacion(SquirlearnWA.notificacionSOAP.listarPorPersonaNotificacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inciNoti.squirlearnws.mycompany.com/Notificacion/listarPorPersonaNotificac" +
            "ionRequest", ReplyAction="http://inciNoti.squirlearnws.mycompany.com/Notificacion/listarPorPersonaNotificac" +
            "ionResponse")]
        System.Threading.Tasks.Task<SquirlearnWA.notificacionSOAP.listarPorPersonaNotificacionResponse> listarPorPersonaNotificacionAsync(SquirlearnWA.notificacionSOAP.listarPorPersonaNotificacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarNotificacion", WrapperNamespace="http://inciNoti.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class insertarNotificacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensaje;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int personaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha;
        
        public insertarNotificacionRequest() {
        }
        
        public insertarNotificacionRequest(string mensaje, int personaId, string fecha) {
            this.mensaje = mensaje;
            this.personaId = personaId;
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarNotificacionResponse", WrapperNamespace="http://inciNoti.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class insertarNotificacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarNotificacionResponse() {
        }
        
        public insertarNotificacionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/")]
    public partial class notificacionDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaField;
        
        private string mensajeField;
        
        private int notificacionIdField;
        
        private bool notificacionIdFieldSpecified;
        
        private personaDto personaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int notificacionId {
            get {
                return this.notificacionIdField;
            }
            set {
                this.notificacionIdField = value;
                this.RaisePropertyChanged("notificacionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool notificacionIdSpecified {
            get {
                return this.notificacionIdFieldSpecified;
            }
            set {
                this.notificacionIdFieldSpecified = value;
                this.RaisePropertyChanged("notificacionIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public personaDto persona {
            get {
                return this.personaField;
            }
            set {
                this.personaField = value;
                this.RaisePropertyChanged("persona");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/")]
    public partial class personaDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string contrasenaField;
        
        private string correoField;
        
        private estadoPersonaDto estadoPersonaField;
        
        private string nombresField;
        
        private int personaIdField;
        
        private bool personaIdFieldSpecified;
        
        private string primerApellidoField;
        
        private rolPersonaDto[] rolPersonaField;
        
        private string segundoApellidoField;
        
        private string ultimaActividadField;
        
        private string usuarioCreacionField;
        
        private string usuarioModificacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("contrasena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public estadoPersonaDto estadoPersona {
            get {
                return this.estadoPersonaField;
            }
            set {
                this.estadoPersonaField = value;
                this.RaisePropertyChanged("estadoPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int personaId {
            get {
                return this.personaIdField;
            }
            set {
                this.personaIdField = value;
                this.RaisePropertyChanged("personaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool personaIdSpecified {
            get {
                return this.personaIdFieldSpecified;
            }
            set {
                this.personaIdFieldSpecified = value;
                this.RaisePropertyChanged("personaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
                this.RaisePropertyChanged("primerApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rolPersona", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public rolPersonaDto[] rolPersona {
            get {
                return this.rolPersonaField;
            }
            set {
                this.rolPersonaField = value;
                this.RaisePropertyChanged("rolPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
                this.RaisePropertyChanged("segundoApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ultimaActividad {
            get {
                return this.ultimaActividadField;
            }
            set {
                this.ultimaActividadField = value;
                this.RaisePropertyChanged("ultimaActividad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string usuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("usuarioCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string usuarioModificacion {
            get {
                return this.usuarioModificacionField;
            }
            set {
                this.usuarioModificacionField = value;
                this.RaisePropertyChanged("usuarioModificacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/")]
    public partial class estadoPersonaDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int estadoPersonaIdField;
        
        private bool estadoPersonaIdFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int estadoPersonaId {
            get {
                return this.estadoPersonaIdField;
            }
            set {
                this.estadoPersonaIdField = value;
                this.RaisePropertyChanged("estadoPersonaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoPersonaIdSpecified {
            get {
                return this.estadoPersonaIdFieldSpecified;
            }
            set {
                this.estadoPersonaIdFieldSpecified = value;
                this.RaisePropertyChanged("estadoPersonaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/")]
    public partial class listadoNotificacionesDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private notificacionDto[] listaField;
        
        private int totalRegistrosField;
        
        private bool totalRegistrosFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lista", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public notificacionDto[] lista {
            get {
                return this.listaField;
            }
            set {
                this.listaField = value;
                this.RaisePropertyChanged("lista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int totalRegistros {
            get {
                return this.totalRegistrosField;
            }
            set {
                this.totalRegistrosField = value;
                this.RaisePropertyChanged("totalRegistros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalRegistrosSpecified {
            get {
                return this.totalRegistrosFieldSpecified;
            }
            set {
                this.totalRegistrosFieldSpecified = value;
                this.RaisePropertyChanged("totalRegistrosSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/")]
    public partial class rolPersonaDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private int rolPersonaIdField;
        
        private bool rolPersonaIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int rolPersonaId {
            get {
                return this.rolPersonaIdField;
            }
            set {
                this.rolPersonaIdField = value;
                this.RaisePropertyChanged("rolPersonaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rolPersonaIdSpecified {
            get {
                return this.rolPersonaIdFieldSpecified;
            }
            set {
                this.rolPersonaIdFieldSpecified = value;
                this.RaisePropertyChanged("rolPersonaIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdNotificacion", WrapperNamespace="http://inciNoti.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class obtenerPorIdNotificacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerPorIdNotificacionRequest() {
        }
        
        public obtenerPorIdNotificacionRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdNotificacionResponse", WrapperNamespace="http://inciNoti.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class obtenerPorIdNotificacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SquirlearnWA.notificacionSOAP.notificacionDto @return;
        
        public obtenerPorIdNotificacionResponse() {
        }
        
        public obtenerPorIdNotificacionResponse(SquirlearnWA.notificacionSOAP.notificacionDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorPersonaNotificacion", WrapperNamespace="http://inciNoti.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class listarPorPersonaNotificacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int personaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pagina;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int registrosPorPagina;
        
        public listarPorPersonaNotificacionRequest() {
        }
        
        public listarPorPersonaNotificacionRequest(int personaId, int pagina, int registrosPorPagina) {
            this.personaId = personaId;
            this.pagina = pagina;
            this.registrosPorPagina = registrosPorPagina;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorPersonaNotificacionResponse", WrapperNamespace="http://inciNoti.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class listarPorPersonaNotificacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SquirlearnWA.notificacionSOAP.listadoNotificacionesDto @return;
        
        public listarPorPersonaNotificacionResponse() {
        }
        
        public listarPorPersonaNotificacionResponse(SquirlearnWA.notificacionSOAP.listadoNotificacionesDto @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NotificacionChannel : SquirlearnWA.notificacionSOAP.Notificacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotificacionClient : System.ServiceModel.ClientBase<SquirlearnWA.notificacionSOAP.Notificacion>, SquirlearnWA.notificacionSOAP.Notificacion {
        
        public NotificacionClient() {
        }
        
        public NotificacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotificacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SquirlearnWA.notificacionSOAP.insertarNotificacionResponse SquirlearnWA.notificacionSOAP.Notificacion.insertarNotificacion(SquirlearnWA.notificacionSOAP.insertarNotificacionRequest request) {
            return base.Channel.insertarNotificacion(request);
        }
        
        public int insertarNotificacion(string mensaje, int personaId, string fecha) {
            SquirlearnWA.notificacionSOAP.insertarNotificacionRequest inValue = new SquirlearnWA.notificacionSOAP.insertarNotificacionRequest();
            inValue.mensaje = mensaje;
            inValue.personaId = personaId;
            inValue.fecha = fecha;
            SquirlearnWA.notificacionSOAP.insertarNotificacionResponse retVal = ((SquirlearnWA.notificacionSOAP.Notificacion)(this)).insertarNotificacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SquirlearnWA.notificacionSOAP.insertarNotificacionResponse> SquirlearnWA.notificacionSOAP.Notificacion.insertarNotificacionAsync(SquirlearnWA.notificacionSOAP.insertarNotificacionRequest request) {
            return base.Channel.insertarNotificacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SquirlearnWA.notificacionSOAP.insertarNotificacionResponse> insertarNotificacionAsync(string mensaje, int personaId, string fecha) {
            SquirlearnWA.notificacionSOAP.insertarNotificacionRequest inValue = new SquirlearnWA.notificacionSOAP.insertarNotificacionRequest();
            inValue.mensaje = mensaje;
            inValue.personaId = personaId;
            inValue.fecha = fecha;
            return ((SquirlearnWA.notificacionSOAP.Notificacion)(this)).insertarNotificacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SquirlearnWA.notificacionSOAP.obtenerPorIdNotificacionResponse SquirlearnWA.notificacionSOAP.Notificacion.obtenerPorIdNotificacion(SquirlearnWA.notificacionSOAP.obtenerPorIdNotificacionRequest request) {
            return base.Channel.obtenerPorIdNotificacion(request);
        }
        
        public SquirlearnWA.notificacionSOAP.notificacionDto obtenerPorIdNotificacion(int id) {
            SquirlearnWA.notificacionSOAP.obtenerPorIdNotificacionRequest inValue = new SquirlearnWA.notificacionSOAP.obtenerPorIdNotificacionRequest();
            inValue.id = id;
            SquirlearnWA.notificacionSOAP.obtenerPorIdNotificacionResponse retVal = ((SquirlearnWA.notificacionSOAP.Notificacion)(this)).obtenerPorIdNotificacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SquirlearnWA.notificacionSOAP.obtenerPorIdNotificacionResponse> SquirlearnWA.notificacionSOAP.Notificacion.obtenerPorIdNotificacionAsync(SquirlearnWA.notificacionSOAP.obtenerPorIdNotificacionRequest request) {
            return base.Channel.obtenerPorIdNotificacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SquirlearnWA.notificacionSOAP.obtenerPorIdNotificacionResponse> obtenerPorIdNotificacionAsync(int id) {
            SquirlearnWA.notificacionSOAP.obtenerPorIdNotificacionRequest inValue = new SquirlearnWA.notificacionSOAP.obtenerPorIdNotificacionRequest();
            inValue.id = id;
            return ((SquirlearnWA.notificacionSOAP.Notificacion)(this)).obtenerPorIdNotificacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SquirlearnWA.notificacionSOAP.listarPorPersonaNotificacionResponse SquirlearnWA.notificacionSOAP.Notificacion.listarPorPersonaNotificacion(SquirlearnWA.notificacionSOAP.listarPorPersonaNotificacionRequest request) {
            return base.Channel.listarPorPersonaNotificacion(request);
        }
        
        public SquirlearnWA.notificacionSOAP.listadoNotificacionesDto listarPorPersonaNotificacion(int personaId, int pagina, int registrosPorPagina) {
            SquirlearnWA.notificacionSOAP.listarPorPersonaNotificacionRequest inValue = new SquirlearnWA.notificacionSOAP.listarPorPersonaNotificacionRequest();
            inValue.personaId = personaId;
            inValue.pagina = pagina;
            inValue.registrosPorPagina = registrosPorPagina;
            SquirlearnWA.notificacionSOAP.listarPorPersonaNotificacionResponse retVal = ((SquirlearnWA.notificacionSOAP.Notificacion)(this)).listarPorPersonaNotificacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SquirlearnWA.notificacionSOAP.listarPorPersonaNotificacionResponse> SquirlearnWA.notificacionSOAP.Notificacion.listarPorPersonaNotificacionAsync(SquirlearnWA.notificacionSOAP.listarPorPersonaNotificacionRequest request) {
            return base.Channel.listarPorPersonaNotificacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SquirlearnWA.notificacionSOAP.listarPorPersonaNotificacionResponse> listarPorPersonaNotificacionAsync(int personaId, int pagina, int registrosPorPagina) {
            SquirlearnWA.notificacionSOAP.listarPorPersonaNotificacionRequest inValue = new SquirlearnWA.notificacionSOAP.listarPorPersonaNotificacionRequest();
            inValue.personaId = personaId;
            inValue.pagina = pagina;
            inValue.registrosPorPagina = registrosPorPagina;
            return ((SquirlearnWA.notificacionSOAP.Notificacion)(this)).listarPorPersonaNotificacionAsync(inValue);
        }
    }
}
