//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SquirlearnWA.colorSOAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://item.squirlearnws.mycompany.com/", ConfigurationName="colorSOAP.Color")]
    public interface Color {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Color/obtenerPorIdColorRequest", ReplyAction="http://item.squirlearnws.mycompany.com/Color/obtenerPorIdColorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SquirlearnWA.colorSOAP.obtenerPorIdColorResponse obtenerPorIdColor(SquirlearnWA.colorSOAP.obtenerPorIdColorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Color/obtenerPorIdColorRequest", ReplyAction="http://item.squirlearnws.mycompany.com/Color/obtenerPorIdColorResponse")]
        System.Threading.Tasks.Task<SquirlearnWA.colorSOAP.obtenerPorIdColorResponse> obtenerPorIdColorAsync(SquirlearnWA.colorSOAP.obtenerPorIdColorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Color/listarTodosColorRequest", ReplyAction="http://item.squirlearnws.mycompany.com/Color/listarTodosColorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SquirlearnWA.colorSOAP.listarTodosColorResponse listarTodosColor(SquirlearnWA.colorSOAP.listarTodosColorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Color/listarTodosColorRequest", ReplyAction="http://item.squirlearnws.mycompany.com/Color/listarTodosColorResponse")]
        System.Threading.Tasks.Task<SquirlearnWA.colorSOAP.listarTodosColorResponse> listarTodosColorAsync(SquirlearnWA.colorSOAP.listarTodosColorRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://item.squirlearnws.mycompany.com/")]
    public partial class colorDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int colorIdField;
        
        private bool colorIdFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int colorId {
            get {
                return this.colorIdField;
            }
            set {
                this.colorIdField = value;
                this.RaisePropertyChanged("colorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool colorIdSpecified {
            get {
                return this.colorIdFieldSpecified;
            }
            set {
                this.colorIdFieldSpecified = value;
                this.RaisePropertyChanged("colorIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdColor", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class obtenerPorIdColorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://item.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerPorIdColorRequest() {
        }
        
        public obtenerPorIdColorRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdColorResponse", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class obtenerPorIdColorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://item.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SquirlearnWA.colorSOAP.colorDto @return;
        
        public obtenerPorIdColorResponse() {
        }
        
        public obtenerPorIdColorResponse(SquirlearnWA.colorSOAP.colorDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosColor", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class listarTodosColorRequest {
        
        public listarTodosColorRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosColorResponse", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class listarTodosColorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://item.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SquirlearnWA.colorSOAP.colorDto[] @return;
        
        public listarTodosColorResponse() {
        }
        
        public listarTodosColorResponse(SquirlearnWA.colorSOAP.colorDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ColorChannel : SquirlearnWA.colorSOAP.Color, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ColorClient : System.ServiceModel.ClientBase<SquirlearnWA.colorSOAP.Color>, SquirlearnWA.colorSOAP.Color {
        
        public ColorClient() {
        }
        
        public ColorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ColorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ColorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ColorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SquirlearnWA.colorSOAP.obtenerPorIdColorResponse SquirlearnWA.colorSOAP.Color.obtenerPorIdColor(SquirlearnWA.colorSOAP.obtenerPorIdColorRequest request) {
            return base.Channel.obtenerPorIdColor(request);
        }
        
        public SquirlearnWA.colorSOAP.colorDto obtenerPorIdColor(int id) {
            SquirlearnWA.colorSOAP.obtenerPorIdColorRequest inValue = new SquirlearnWA.colorSOAP.obtenerPorIdColorRequest();
            inValue.id = id;
            SquirlearnWA.colorSOAP.obtenerPorIdColorResponse retVal = ((SquirlearnWA.colorSOAP.Color)(this)).obtenerPorIdColor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SquirlearnWA.colorSOAP.obtenerPorIdColorResponse> SquirlearnWA.colorSOAP.Color.obtenerPorIdColorAsync(SquirlearnWA.colorSOAP.obtenerPorIdColorRequest request) {
            return base.Channel.obtenerPorIdColorAsync(request);
        }
        
        public System.Threading.Tasks.Task<SquirlearnWA.colorSOAP.obtenerPorIdColorResponse> obtenerPorIdColorAsync(int id) {
            SquirlearnWA.colorSOAP.obtenerPorIdColorRequest inValue = new SquirlearnWA.colorSOAP.obtenerPorIdColorRequest();
            inValue.id = id;
            return ((SquirlearnWA.colorSOAP.Color)(this)).obtenerPorIdColorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SquirlearnWA.colorSOAP.listarTodosColorResponse SquirlearnWA.colorSOAP.Color.listarTodosColor(SquirlearnWA.colorSOAP.listarTodosColorRequest request) {
            return base.Channel.listarTodosColor(request);
        }
        
        public SquirlearnWA.colorSOAP.colorDto[] listarTodosColor() {
            SquirlearnWA.colorSOAP.listarTodosColorRequest inValue = new SquirlearnWA.colorSOAP.listarTodosColorRequest();
            SquirlearnWA.colorSOAP.listarTodosColorResponse retVal = ((SquirlearnWA.colorSOAP.Color)(this)).listarTodosColor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SquirlearnWA.colorSOAP.listarTodosColorResponse> SquirlearnWA.colorSOAP.Color.listarTodosColorAsync(SquirlearnWA.colorSOAP.listarTodosColorRequest request) {
            return base.Channel.listarTodosColorAsync(request);
        }
        
        public System.Threading.Tasks.Task<SquirlearnWA.colorSOAP.listarTodosColorResponse> listarTodosColorAsync() {
            SquirlearnWA.colorSOAP.listarTodosColorRequest inValue = new SquirlearnWA.colorSOAP.listarTodosColorRequest();
            return ((SquirlearnWA.colorSOAP.Color)(this)).listarTodosColorAsync(inValue);
        }
    }
}
