//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SquirlearnWA.motivoSOAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", ConfigurationName="motivoSOAP.Motivo")]
    public interface Motivo {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://inciNoti.squirlearnws.mycompany.com/Motivo/listarTodosMotivoRequest", ReplyAction="http://inciNoti.squirlearnws.mycompany.com/Motivo/listarTodosMotivoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(obtenerPorIdMotivoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(obtenerPorIdMotivo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarTodosMotivo))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SquirlearnWA.motivoSOAP.listarTodosMotivoResponse listarTodosMotivo(SquirlearnWA.motivoSOAP.listarTodosMotivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inciNoti.squirlearnws.mycompany.com/Motivo/listarTodosMotivoRequest", ReplyAction="http://inciNoti.squirlearnws.mycompany.com/Motivo/listarTodosMotivoResponse")]
        System.Threading.Tasks.Task<SquirlearnWA.motivoSOAP.listarTodosMotivoResponse> listarTodosMotivoAsync(SquirlearnWA.motivoSOAP.listarTodosMotivoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://inciNoti.squirlearnws.mycompany.com/Motivo/obtenerPorIdMotivoRequest", ReplyAction="http://inciNoti.squirlearnws.mycompany.com/Motivo/obtenerPorIdMotivoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(obtenerPorIdMotivoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(obtenerPorIdMotivo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listarTodosMotivo))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SquirlearnWA.motivoSOAP.obtenerPorIdMotivoResponse1 obtenerPorIdMotivo(SquirlearnWA.motivoSOAP.obtenerPorIdMotivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inciNoti.squirlearnws.mycompany.com/Motivo/obtenerPorIdMotivoRequest", ReplyAction="http://inciNoti.squirlearnws.mycompany.com/Motivo/obtenerPorIdMotivoResponse")]
        System.Threading.Tasks.Task<SquirlearnWA.motivoSOAP.obtenerPorIdMotivoResponse1> obtenerPorIdMotivoAsync(SquirlearnWA.motivoSOAP.obtenerPorIdMotivoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/")]
    public partial class motivoDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int motivoIdField;
        
        private bool motivoIdFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int motivoId {
            get {
                return this.motivoIdField;
            }
            set {
                this.motivoIdField = value;
                this.RaisePropertyChanged("motivoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool motivoIdSpecified {
            get {
                return this.motivoIdFieldSpecified;
            }
            set {
                this.motivoIdFieldSpecified = value;
                this.RaisePropertyChanged("motivoIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/")]
    public partial class obtenerPorIdMotivoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private motivoDto returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public motivoDto @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/")]
    public partial class obtenerPorIdMotivo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/")]
    public partial class listarTodosMotivo : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosMotivo", WrapperNamespace="http://inciNoti.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class listarTodosMotivoRequest {
        
        public listarTodosMotivoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosMotivoResponse", WrapperNamespace="http://inciNoti.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class listarTodosMotivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] @return;
        
        public listarTodosMotivoResponse() {
        }
        
        public listarTodosMotivoResponse(object[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdMotivo", WrapperNamespace="http://inciNoti.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class obtenerPorIdMotivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerPorIdMotivoRequest() {
        }
        
        public obtenerPorIdMotivoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdMotivoResponse", WrapperNamespace="http://inciNoti.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class obtenerPorIdMotivoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inciNoti.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SquirlearnWA.motivoSOAP.motivoDto @return;
        
        public obtenerPorIdMotivoResponse1() {
        }
        
        public obtenerPorIdMotivoResponse1(SquirlearnWA.motivoSOAP.motivoDto @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MotivoChannel : SquirlearnWA.motivoSOAP.Motivo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MotivoClient : System.ServiceModel.ClientBase<SquirlearnWA.motivoSOAP.Motivo>, SquirlearnWA.motivoSOAP.Motivo {
        
        public MotivoClient() {
        }
        
        public MotivoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MotivoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MotivoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MotivoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SquirlearnWA.motivoSOAP.listarTodosMotivoResponse SquirlearnWA.motivoSOAP.Motivo.listarTodosMotivo(SquirlearnWA.motivoSOAP.listarTodosMotivoRequest request) {
            return base.Channel.listarTodosMotivo(request);
        }
        
        public object[] listarTodosMotivo() {
            SquirlearnWA.motivoSOAP.listarTodosMotivoRequest inValue = new SquirlearnWA.motivoSOAP.listarTodosMotivoRequest();
            SquirlearnWA.motivoSOAP.listarTodosMotivoResponse retVal = ((SquirlearnWA.motivoSOAP.Motivo)(this)).listarTodosMotivo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SquirlearnWA.motivoSOAP.listarTodosMotivoResponse> SquirlearnWA.motivoSOAP.Motivo.listarTodosMotivoAsync(SquirlearnWA.motivoSOAP.listarTodosMotivoRequest request) {
            return base.Channel.listarTodosMotivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SquirlearnWA.motivoSOAP.listarTodosMotivoResponse> listarTodosMotivoAsync() {
            SquirlearnWA.motivoSOAP.listarTodosMotivoRequest inValue = new SquirlearnWA.motivoSOAP.listarTodosMotivoRequest();
            return ((SquirlearnWA.motivoSOAP.Motivo)(this)).listarTodosMotivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SquirlearnWA.motivoSOAP.obtenerPorIdMotivoResponse1 SquirlearnWA.motivoSOAP.Motivo.obtenerPorIdMotivo(SquirlearnWA.motivoSOAP.obtenerPorIdMotivoRequest request) {
            return base.Channel.obtenerPorIdMotivo(request);
        }
        
        public SquirlearnWA.motivoSOAP.motivoDto obtenerPorIdMotivo(int id) {
            SquirlearnWA.motivoSOAP.obtenerPorIdMotivoRequest inValue = new SquirlearnWA.motivoSOAP.obtenerPorIdMotivoRequest();
            inValue.id = id;
            SquirlearnWA.motivoSOAP.obtenerPorIdMotivoResponse1 retVal = ((SquirlearnWA.motivoSOAP.Motivo)(this)).obtenerPorIdMotivo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SquirlearnWA.motivoSOAP.obtenerPorIdMotivoResponse1> SquirlearnWA.motivoSOAP.Motivo.obtenerPorIdMotivoAsync(SquirlearnWA.motivoSOAP.obtenerPorIdMotivoRequest request) {
            return base.Channel.obtenerPorIdMotivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SquirlearnWA.motivoSOAP.obtenerPorIdMotivoResponse1> obtenerPorIdMotivoAsync(int id) {
            SquirlearnWA.motivoSOAP.obtenerPorIdMotivoRequest inValue = new SquirlearnWA.motivoSOAP.obtenerPorIdMotivoRequest();
            inValue.id = id;
            return ((SquirlearnWA.motivoSOAP.Motivo)(this)).obtenerPorIdMotivoAsync(inValue);
        }
    }
}
