//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SquirlearnWA.categoriaSOAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://item.squirlearnws.mycompany.com/", ConfigurationName="categoriaSOAP.Categoria")]
    public interface Categoria {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Categoria/obtenerPorIdCategoriaRequest", ReplyAction="http://item.squirlearnws.mycompany.com/Categoria/obtenerPorIdCategoriaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SquirlearnWA.categoriaSOAP.obtenerPorIdCategoriaResponse obtenerPorIdCategoria(SquirlearnWA.categoriaSOAP.obtenerPorIdCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Categoria/obtenerPorIdCategoriaRequest", ReplyAction="http://item.squirlearnws.mycompany.com/Categoria/obtenerPorIdCategoriaResponse")]
        System.Threading.Tasks.Task<SquirlearnWA.categoriaSOAP.obtenerPorIdCategoriaResponse> obtenerPorIdCategoriaAsync(SquirlearnWA.categoriaSOAP.obtenerPorIdCategoriaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Categoria/listarTodosCategoriaRequest", ReplyAction="http://item.squirlearnws.mycompany.com/Categoria/listarTodosCategoriaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SquirlearnWA.categoriaSOAP.listarTodosCategoriaResponse listarTodosCategoria(SquirlearnWA.categoriaSOAP.listarTodosCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Categoria/listarTodosCategoriaRequest", ReplyAction="http://item.squirlearnws.mycompany.com/Categoria/listarTodosCategoriaResponse")]
        System.Threading.Tasks.Task<SquirlearnWA.categoriaSOAP.listarTodosCategoriaResponse> listarTodosCategoriaAsync(SquirlearnWA.categoriaSOAP.listarTodosCategoriaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://item.squirlearnws.mycompany.com/")]
    public partial class categoriaDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int categoriaIdField;
        
        private bool categoriaIdFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int categoriaId {
            get {
                return this.categoriaIdField;
            }
            set {
                this.categoriaIdField = value;
                this.RaisePropertyChanged("categoriaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoriaIdSpecified {
            get {
                return this.categoriaIdFieldSpecified;
            }
            set {
                this.categoriaIdFieldSpecified = value;
                this.RaisePropertyChanged("categoriaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdCategoria", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class obtenerPorIdCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://item.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerPorIdCategoriaRequest() {
        }
        
        public obtenerPorIdCategoriaRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdCategoriaResponse", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class obtenerPorIdCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://item.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SquirlearnWA.categoriaSOAP.categoriaDto @return;
        
        public obtenerPorIdCategoriaResponse() {
        }
        
        public obtenerPorIdCategoriaResponse(SquirlearnWA.categoriaSOAP.categoriaDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosCategoria", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class listarTodosCategoriaRequest {
        
        public listarTodosCategoriaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosCategoriaResponse", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class listarTodosCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://item.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SquirlearnWA.categoriaSOAP.categoriaDto[] @return;
        
        public listarTodosCategoriaResponse() {
        }
        
        public listarTodosCategoriaResponse(SquirlearnWA.categoriaSOAP.categoriaDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CategoriaChannel : SquirlearnWA.categoriaSOAP.Categoria, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoriaClient : System.ServiceModel.ClientBase<SquirlearnWA.categoriaSOAP.Categoria>, SquirlearnWA.categoriaSOAP.Categoria {
        
        public CategoriaClient() {
        }
        
        public CategoriaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoriaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SquirlearnWA.categoriaSOAP.obtenerPorIdCategoriaResponse SquirlearnWA.categoriaSOAP.Categoria.obtenerPorIdCategoria(SquirlearnWA.categoriaSOAP.obtenerPorIdCategoriaRequest request) {
            return base.Channel.obtenerPorIdCategoria(request);
        }
        
        public SquirlearnWA.categoriaSOAP.categoriaDto obtenerPorIdCategoria(int id) {
            SquirlearnWA.categoriaSOAP.obtenerPorIdCategoriaRequest inValue = new SquirlearnWA.categoriaSOAP.obtenerPorIdCategoriaRequest();
            inValue.id = id;
            SquirlearnWA.categoriaSOAP.obtenerPorIdCategoriaResponse retVal = ((SquirlearnWA.categoriaSOAP.Categoria)(this)).obtenerPorIdCategoria(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SquirlearnWA.categoriaSOAP.obtenerPorIdCategoriaResponse> SquirlearnWA.categoriaSOAP.Categoria.obtenerPorIdCategoriaAsync(SquirlearnWA.categoriaSOAP.obtenerPorIdCategoriaRequest request) {
            return base.Channel.obtenerPorIdCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SquirlearnWA.categoriaSOAP.obtenerPorIdCategoriaResponse> obtenerPorIdCategoriaAsync(int id) {
            SquirlearnWA.categoriaSOAP.obtenerPorIdCategoriaRequest inValue = new SquirlearnWA.categoriaSOAP.obtenerPorIdCategoriaRequest();
            inValue.id = id;
            return ((SquirlearnWA.categoriaSOAP.Categoria)(this)).obtenerPorIdCategoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SquirlearnWA.categoriaSOAP.listarTodosCategoriaResponse SquirlearnWA.categoriaSOAP.Categoria.listarTodosCategoria(SquirlearnWA.categoriaSOAP.listarTodosCategoriaRequest request) {
            return base.Channel.listarTodosCategoria(request);
        }
        
        public SquirlearnWA.categoriaSOAP.categoriaDto[] listarTodosCategoria() {
            SquirlearnWA.categoriaSOAP.listarTodosCategoriaRequest inValue = new SquirlearnWA.categoriaSOAP.listarTodosCategoriaRequest();
            SquirlearnWA.categoriaSOAP.listarTodosCategoriaResponse retVal = ((SquirlearnWA.categoriaSOAP.Categoria)(this)).listarTodosCategoria(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SquirlearnWA.categoriaSOAP.listarTodosCategoriaResponse> SquirlearnWA.categoriaSOAP.Categoria.listarTodosCategoriaAsync(SquirlearnWA.categoriaSOAP.listarTodosCategoriaRequest request) {
            return base.Channel.listarTodosCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SquirlearnWA.categoriaSOAP.listarTodosCategoriaResponse> listarTodosCategoriaAsync() {
            SquirlearnWA.categoriaSOAP.listarTodosCategoriaRequest inValue = new SquirlearnWA.categoriaSOAP.listarTodosCategoriaRequest();
            return ((SquirlearnWA.categoriaSOAP.Categoria)(this)).listarTodosCategoriaAsync(inValue);
        }
    }
}
