//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SquirlearnWA.formatoSOAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://item.squirlearnws.mycompany.com/", ConfigurationName="formatoSOAP.Formato")]
    public interface Formato {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Formato/listarTodosFormatoRequest", ReplyAction="http://item.squirlearnws.mycompany.com/Formato/listarTodosFormatoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SquirlearnWA.formatoSOAP.listarTodosFormatoResponse listarTodosFormato(SquirlearnWA.formatoSOAP.listarTodosFormatoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Formato/listarTodosFormatoRequest", ReplyAction="http://item.squirlearnws.mycompany.com/Formato/listarTodosFormatoResponse")]
        System.Threading.Tasks.Task<SquirlearnWA.formatoSOAP.listarTodosFormatoResponse> listarTodosFormatoAsync(SquirlearnWA.formatoSOAP.listarTodosFormatoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Formato/obtenerPorIdFormatoRequest", ReplyAction="http://item.squirlearnws.mycompany.com/Formato/obtenerPorIdFormatoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SquirlearnWA.formatoSOAP.obtenerPorIdFormatoResponse obtenerPorIdFormato(SquirlearnWA.formatoSOAP.obtenerPorIdFormatoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Formato/obtenerPorIdFormatoRequest", ReplyAction="http://item.squirlearnws.mycompany.com/Formato/obtenerPorIdFormatoResponse")]
        System.Threading.Tasks.Task<SquirlearnWA.formatoSOAP.obtenerPorIdFormatoResponse> obtenerPorIdFormatoAsync(SquirlearnWA.formatoSOAP.obtenerPorIdFormatoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://item.squirlearnws.mycompany.com/")]
    public partial class formatoDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int formatoIdField;
        
        private bool formatoIdFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int formatoId {
            get {
                return this.formatoIdField;
            }
            set {
                this.formatoIdField = value;
                this.RaisePropertyChanged("formatoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool formatoIdSpecified {
            get {
                return this.formatoIdFieldSpecified;
            }
            set {
                this.formatoIdFieldSpecified = value;
                this.RaisePropertyChanged("formatoIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosFormato", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class listarTodosFormatoRequest {
        
        public listarTodosFormatoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosFormatoResponse", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class listarTodosFormatoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://item.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SquirlearnWA.formatoSOAP.formatoDto[] @return;
        
        public listarTodosFormatoResponse() {
        }
        
        public listarTodosFormatoResponse(SquirlearnWA.formatoSOAP.formatoDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdFormato", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class obtenerPorIdFormatoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://item.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerPorIdFormatoRequest() {
        }
        
        public obtenerPorIdFormatoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdFormatoResponse", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class obtenerPorIdFormatoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://item.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SquirlearnWA.formatoSOAP.formatoDto @return;
        
        public obtenerPorIdFormatoResponse() {
        }
        
        public obtenerPorIdFormatoResponse(SquirlearnWA.formatoSOAP.formatoDto @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FormatoChannel : SquirlearnWA.formatoSOAP.Formato, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FormatoClient : System.ServiceModel.ClientBase<SquirlearnWA.formatoSOAP.Formato>, SquirlearnWA.formatoSOAP.Formato {
        
        public FormatoClient() {
        }
        
        public FormatoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FormatoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormatoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormatoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SquirlearnWA.formatoSOAP.listarTodosFormatoResponse SquirlearnWA.formatoSOAP.Formato.listarTodosFormato(SquirlearnWA.formatoSOAP.listarTodosFormatoRequest request) {
            return base.Channel.listarTodosFormato(request);
        }
        
        public SquirlearnWA.formatoSOAP.formatoDto[] listarTodosFormato() {
            SquirlearnWA.formatoSOAP.listarTodosFormatoRequest inValue = new SquirlearnWA.formatoSOAP.listarTodosFormatoRequest();
            SquirlearnWA.formatoSOAP.listarTodosFormatoResponse retVal = ((SquirlearnWA.formatoSOAP.Formato)(this)).listarTodosFormato(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SquirlearnWA.formatoSOAP.listarTodosFormatoResponse> SquirlearnWA.formatoSOAP.Formato.listarTodosFormatoAsync(SquirlearnWA.formatoSOAP.listarTodosFormatoRequest request) {
            return base.Channel.listarTodosFormatoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SquirlearnWA.formatoSOAP.listarTodosFormatoResponse> listarTodosFormatoAsync() {
            SquirlearnWA.formatoSOAP.listarTodosFormatoRequest inValue = new SquirlearnWA.formatoSOAP.listarTodosFormatoRequest();
            return ((SquirlearnWA.formatoSOAP.Formato)(this)).listarTodosFormatoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SquirlearnWA.formatoSOAP.obtenerPorIdFormatoResponse SquirlearnWA.formatoSOAP.Formato.obtenerPorIdFormato(SquirlearnWA.formatoSOAP.obtenerPorIdFormatoRequest request) {
            return base.Channel.obtenerPorIdFormato(request);
        }
        
        public SquirlearnWA.formatoSOAP.formatoDto obtenerPorIdFormato(int id) {
            SquirlearnWA.formatoSOAP.obtenerPorIdFormatoRequest inValue = new SquirlearnWA.formatoSOAP.obtenerPorIdFormatoRequest();
            inValue.id = id;
            SquirlearnWA.formatoSOAP.obtenerPorIdFormatoResponse retVal = ((SquirlearnWA.formatoSOAP.Formato)(this)).obtenerPorIdFormato(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SquirlearnWA.formatoSOAP.obtenerPorIdFormatoResponse> SquirlearnWA.formatoSOAP.Formato.obtenerPorIdFormatoAsync(SquirlearnWA.formatoSOAP.obtenerPorIdFormatoRequest request) {
            return base.Channel.obtenerPorIdFormatoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SquirlearnWA.formatoSOAP.obtenerPorIdFormatoResponse> obtenerPorIdFormatoAsync(int id) {
            SquirlearnWA.formatoSOAP.obtenerPorIdFormatoRequest inValue = new SquirlearnWA.formatoSOAP.obtenerPorIdFormatoRequest();
            inValue.id = id;
            return ((SquirlearnWA.formatoSOAP.Formato)(this)).obtenerPorIdFormatoAsync(inValue);
        }
    }
}
