//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SquirlearnWA.condicionSOAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://item.squirlearnws.mycompany.com/", ConfigurationName="condicionSOAP.Condicion")]
    public interface Condicion {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Condicion/obtenerPorIdCondicionRequest", ReplyAction="http://item.squirlearnws.mycompany.com/Condicion/obtenerPorIdCondicionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SquirlearnWA.condicionSOAP.obtenerPorIdCondicionResponse obtenerPorIdCondicion(SquirlearnWA.condicionSOAP.obtenerPorIdCondicionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Condicion/obtenerPorIdCondicionRequest", ReplyAction="http://item.squirlearnws.mycompany.com/Condicion/obtenerPorIdCondicionResponse")]
        System.Threading.Tasks.Task<SquirlearnWA.condicionSOAP.obtenerPorIdCondicionResponse> obtenerPorIdCondicionAsync(SquirlearnWA.condicionSOAP.obtenerPorIdCondicionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Condicion/listarTodosCondicionRequest", ReplyAction="http://item.squirlearnws.mycompany.com/Condicion/listarTodosCondicionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SquirlearnWA.condicionSOAP.listarTodosCondicionResponse listarTodosCondicion(SquirlearnWA.condicionSOAP.listarTodosCondicionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Condicion/listarTodosCondicionRequest", ReplyAction="http://item.squirlearnws.mycompany.com/Condicion/listarTodosCondicionResponse")]
        System.Threading.Tasks.Task<SquirlearnWA.condicionSOAP.listarTodosCondicionResponse> listarTodosCondicionAsync(SquirlearnWA.condicionSOAP.listarTodosCondicionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://item.squirlearnws.mycompany.com/")]
    public partial class condicionDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int condicionIdField;
        
        private bool condicionIdFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int condicionId {
            get {
                return this.condicionIdField;
            }
            set {
                this.condicionIdField = value;
                this.RaisePropertyChanged("condicionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool condicionIdSpecified {
            get {
                return this.condicionIdFieldSpecified;
            }
            set {
                this.condicionIdFieldSpecified = value;
                this.RaisePropertyChanged("condicionIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdCondicion", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class obtenerPorIdCondicionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://item.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerPorIdCondicionRequest() {
        }
        
        public obtenerPorIdCondicionRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdCondicionResponse", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class obtenerPorIdCondicionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://item.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SquirlearnWA.condicionSOAP.condicionDto @return;
        
        public obtenerPorIdCondicionResponse() {
        }
        
        public obtenerPorIdCondicionResponse(SquirlearnWA.condicionSOAP.condicionDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosCondicion", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class listarTodosCondicionRequest {
        
        public listarTodosCondicionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosCondicionResponse", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class listarTodosCondicionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://item.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SquirlearnWA.condicionSOAP.condicionDto[] @return;
        
        public listarTodosCondicionResponse() {
        }
        
        public listarTodosCondicionResponse(SquirlearnWA.condicionSOAP.condicionDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CondicionChannel : SquirlearnWA.condicionSOAP.Condicion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CondicionClient : System.ServiceModel.ClientBase<SquirlearnWA.condicionSOAP.Condicion>, SquirlearnWA.condicionSOAP.Condicion {
        
        public CondicionClient() {
        }
        
        public CondicionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CondicionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CondicionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CondicionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SquirlearnWA.condicionSOAP.obtenerPorIdCondicionResponse SquirlearnWA.condicionSOAP.Condicion.obtenerPorIdCondicion(SquirlearnWA.condicionSOAP.obtenerPorIdCondicionRequest request) {
            return base.Channel.obtenerPorIdCondicion(request);
        }
        
        public SquirlearnWA.condicionSOAP.condicionDto obtenerPorIdCondicion(int id) {
            SquirlearnWA.condicionSOAP.obtenerPorIdCondicionRequest inValue = new SquirlearnWA.condicionSOAP.obtenerPorIdCondicionRequest();
            inValue.id = id;
            SquirlearnWA.condicionSOAP.obtenerPorIdCondicionResponse retVal = ((SquirlearnWA.condicionSOAP.Condicion)(this)).obtenerPorIdCondicion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SquirlearnWA.condicionSOAP.obtenerPorIdCondicionResponse> SquirlearnWA.condicionSOAP.Condicion.obtenerPorIdCondicionAsync(SquirlearnWA.condicionSOAP.obtenerPorIdCondicionRequest request) {
            return base.Channel.obtenerPorIdCondicionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SquirlearnWA.condicionSOAP.obtenerPorIdCondicionResponse> obtenerPorIdCondicionAsync(int id) {
            SquirlearnWA.condicionSOAP.obtenerPorIdCondicionRequest inValue = new SquirlearnWA.condicionSOAP.obtenerPorIdCondicionRequest();
            inValue.id = id;
            return ((SquirlearnWA.condicionSOAP.Condicion)(this)).obtenerPorIdCondicionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SquirlearnWA.condicionSOAP.listarTodosCondicionResponse SquirlearnWA.condicionSOAP.Condicion.listarTodosCondicion(SquirlearnWA.condicionSOAP.listarTodosCondicionRequest request) {
            return base.Channel.listarTodosCondicion(request);
        }
        
        public SquirlearnWA.condicionSOAP.condicionDto[] listarTodosCondicion() {
            SquirlearnWA.condicionSOAP.listarTodosCondicionRequest inValue = new SquirlearnWA.condicionSOAP.listarTodosCondicionRequest();
            SquirlearnWA.condicionSOAP.listarTodosCondicionResponse retVal = ((SquirlearnWA.condicionSOAP.Condicion)(this)).listarTodosCondicion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SquirlearnWA.condicionSOAP.listarTodosCondicionResponse> SquirlearnWA.condicionSOAP.Condicion.listarTodosCondicionAsync(SquirlearnWA.condicionSOAP.listarTodosCondicionRequest request) {
            return base.Channel.listarTodosCondicionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SquirlearnWA.condicionSOAP.listarTodosCondicionResponse> listarTodosCondicionAsync() {
            SquirlearnWA.condicionSOAP.listarTodosCondicionRequest inValue = new SquirlearnWA.condicionSOAP.listarTodosCondicionRequest();
            return ((SquirlearnWA.condicionSOAP.Condicion)(this)).listarTodosCondicionAsync(inValue);
        }
    }
}
