//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SquirlearnWA.subcategoriaSOAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://item.squirlearnws.mycompany.com/", ConfigurationName="subcategoriaSOAP.Subcategoria")]
    public interface Subcategoria {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Subcategoria/listarPorCategoriaSubcategori" +
            "aRequest", ReplyAction="http://item.squirlearnws.mycompany.com/Subcategoria/listarPorCategoriaSubcategori" +
            "aResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SquirlearnWA.subcategoriaSOAP.listarPorCategoriaSubcategoriaResponse listarPorCategoriaSubcategoria(SquirlearnWA.subcategoriaSOAP.listarPorCategoriaSubcategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Subcategoria/listarPorCategoriaSubcategori" +
            "aRequest", ReplyAction="http://item.squirlearnws.mycompany.com/Subcategoria/listarPorCategoriaSubcategori" +
            "aResponse")]
        System.Threading.Tasks.Task<SquirlearnWA.subcategoriaSOAP.listarPorCategoriaSubcategoriaResponse> listarPorCategoriaSubcategoriaAsync(SquirlearnWA.subcategoriaSOAP.listarPorCategoriaSubcategoriaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Subcategoria/obtenerPorIdSubcategoriaReque" +
            "st", ReplyAction="http://item.squirlearnws.mycompany.com/Subcategoria/obtenerPorIdSubcategoriaRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SquirlearnWA.subcategoriaSOAP.obtenerPorIdSubcategoriaResponse obtenerPorIdSubcategoria(SquirlearnWA.subcategoriaSOAP.obtenerPorIdSubcategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Subcategoria/obtenerPorIdSubcategoriaReque" +
            "st", ReplyAction="http://item.squirlearnws.mycompany.com/Subcategoria/obtenerPorIdSubcategoriaRespo" +
            "nse")]
        System.Threading.Tasks.Task<SquirlearnWA.subcategoriaSOAP.obtenerPorIdSubcategoriaResponse> obtenerPorIdSubcategoriaAsync(SquirlearnWA.subcategoriaSOAP.obtenerPorIdSubcategoriaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Subcategoria/listarTodosSubcategoriaReques" +
            "t", ReplyAction="http://item.squirlearnws.mycompany.com/Subcategoria/listarTodosSubcategoriaRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SquirlearnWA.subcategoriaSOAP.listarTodosSubcategoriaResponse listarTodosSubcategoria(SquirlearnWA.subcategoriaSOAP.listarTodosSubcategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://item.squirlearnws.mycompany.com/Subcategoria/listarTodosSubcategoriaReques" +
            "t", ReplyAction="http://item.squirlearnws.mycompany.com/Subcategoria/listarTodosSubcategoriaRespon" +
            "se")]
        System.Threading.Tasks.Task<SquirlearnWA.subcategoriaSOAP.listarTodosSubcategoriaResponse> listarTodosSubcategoriaAsync(SquirlearnWA.subcategoriaSOAP.listarTodosSubcategoriaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://item.squirlearnws.mycompany.com/")]
    public partial class subcategoriaDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private categoriaDto categoriaField;
        
        private string nombreField;
        
        private int subcategoriaIdField;
        
        private bool subcategoriaIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoriaDto categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int subcategoriaId {
            get {
                return this.subcategoriaIdField;
            }
            set {
                this.subcategoriaIdField = value;
                this.RaisePropertyChanged("subcategoriaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subcategoriaIdSpecified {
            get {
                return this.subcategoriaIdFieldSpecified;
            }
            set {
                this.subcategoriaIdFieldSpecified = value;
                this.RaisePropertyChanged("subcategoriaIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://item.squirlearnws.mycompany.com/")]
    public partial class categoriaDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int categoriaIdField;
        
        private bool categoriaIdFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int categoriaId {
            get {
                return this.categoriaIdField;
            }
            set {
                this.categoriaIdField = value;
                this.RaisePropertyChanged("categoriaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoriaIdSpecified {
            get {
                return this.categoriaIdFieldSpecified;
            }
            set {
                this.categoriaIdFieldSpecified = value;
                this.RaisePropertyChanged("categoriaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorCategoriaSubcategoria", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class listarPorCategoriaSubcategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://item.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int categoriaId;
        
        public listarPorCategoriaSubcategoriaRequest() {
        }
        
        public listarPorCategoriaSubcategoriaRequest(int categoriaId) {
            this.categoriaId = categoriaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorCategoriaSubcategoriaResponse", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class listarPorCategoriaSubcategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://item.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SquirlearnWA.subcategoriaSOAP.subcategoriaDto[] @return;
        
        public listarPorCategoriaSubcategoriaResponse() {
        }
        
        public listarPorCategoriaSubcategoriaResponse(SquirlearnWA.subcategoriaSOAP.subcategoriaDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdSubcategoria", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class obtenerPorIdSubcategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://item.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerPorIdSubcategoriaRequest() {
        }
        
        public obtenerPorIdSubcategoriaRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdSubcategoriaResponse", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class obtenerPorIdSubcategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://item.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SquirlearnWA.subcategoriaSOAP.subcategoriaDto @return;
        
        public obtenerPorIdSubcategoriaResponse() {
        }
        
        public obtenerPorIdSubcategoriaResponse(SquirlearnWA.subcategoriaSOAP.subcategoriaDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosSubcategoria", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class listarTodosSubcategoriaRequest {
        
        public listarTodosSubcategoriaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosSubcategoriaResponse", WrapperNamespace="http://item.squirlearnws.mycompany.com/", IsWrapped=true)]
    public partial class listarTodosSubcategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://item.squirlearnws.mycompany.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SquirlearnWA.subcategoriaSOAP.subcategoriaDto[] @return;
        
        public listarTodosSubcategoriaResponse() {
        }
        
        public listarTodosSubcategoriaResponse(SquirlearnWA.subcategoriaSOAP.subcategoriaDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SubcategoriaChannel : SquirlearnWA.subcategoriaSOAP.Subcategoria, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubcategoriaClient : System.ServiceModel.ClientBase<SquirlearnWA.subcategoriaSOAP.Subcategoria>, SquirlearnWA.subcategoriaSOAP.Subcategoria {
        
        public SubcategoriaClient() {
        }
        
        public SubcategoriaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubcategoriaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubcategoriaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubcategoriaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SquirlearnWA.subcategoriaSOAP.listarPorCategoriaSubcategoriaResponse SquirlearnWA.subcategoriaSOAP.Subcategoria.listarPorCategoriaSubcategoria(SquirlearnWA.subcategoriaSOAP.listarPorCategoriaSubcategoriaRequest request) {
            return base.Channel.listarPorCategoriaSubcategoria(request);
        }
        
        public SquirlearnWA.subcategoriaSOAP.subcategoriaDto[] listarPorCategoriaSubcategoria(int categoriaId) {
            SquirlearnWA.subcategoriaSOAP.listarPorCategoriaSubcategoriaRequest inValue = new SquirlearnWA.subcategoriaSOAP.listarPorCategoriaSubcategoriaRequest();
            inValue.categoriaId = categoriaId;
            SquirlearnWA.subcategoriaSOAP.listarPorCategoriaSubcategoriaResponse retVal = ((SquirlearnWA.subcategoriaSOAP.Subcategoria)(this)).listarPorCategoriaSubcategoria(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SquirlearnWA.subcategoriaSOAP.listarPorCategoriaSubcategoriaResponse> SquirlearnWA.subcategoriaSOAP.Subcategoria.listarPorCategoriaSubcategoriaAsync(SquirlearnWA.subcategoriaSOAP.listarPorCategoriaSubcategoriaRequest request) {
            return base.Channel.listarPorCategoriaSubcategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SquirlearnWA.subcategoriaSOAP.listarPorCategoriaSubcategoriaResponse> listarPorCategoriaSubcategoriaAsync(int categoriaId) {
            SquirlearnWA.subcategoriaSOAP.listarPorCategoriaSubcategoriaRequest inValue = new SquirlearnWA.subcategoriaSOAP.listarPorCategoriaSubcategoriaRequest();
            inValue.categoriaId = categoriaId;
            return ((SquirlearnWA.subcategoriaSOAP.Subcategoria)(this)).listarPorCategoriaSubcategoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SquirlearnWA.subcategoriaSOAP.obtenerPorIdSubcategoriaResponse SquirlearnWA.subcategoriaSOAP.Subcategoria.obtenerPorIdSubcategoria(SquirlearnWA.subcategoriaSOAP.obtenerPorIdSubcategoriaRequest request) {
            return base.Channel.obtenerPorIdSubcategoria(request);
        }
        
        public SquirlearnWA.subcategoriaSOAP.subcategoriaDto obtenerPorIdSubcategoria(int id) {
            SquirlearnWA.subcategoriaSOAP.obtenerPorIdSubcategoriaRequest inValue = new SquirlearnWA.subcategoriaSOAP.obtenerPorIdSubcategoriaRequest();
            inValue.id = id;
            SquirlearnWA.subcategoriaSOAP.obtenerPorIdSubcategoriaResponse retVal = ((SquirlearnWA.subcategoriaSOAP.Subcategoria)(this)).obtenerPorIdSubcategoria(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SquirlearnWA.subcategoriaSOAP.obtenerPorIdSubcategoriaResponse> SquirlearnWA.subcategoriaSOAP.Subcategoria.obtenerPorIdSubcategoriaAsync(SquirlearnWA.subcategoriaSOAP.obtenerPorIdSubcategoriaRequest request) {
            return base.Channel.obtenerPorIdSubcategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SquirlearnWA.subcategoriaSOAP.obtenerPorIdSubcategoriaResponse> obtenerPorIdSubcategoriaAsync(int id) {
            SquirlearnWA.subcategoriaSOAP.obtenerPorIdSubcategoriaRequest inValue = new SquirlearnWA.subcategoriaSOAP.obtenerPorIdSubcategoriaRequest();
            inValue.id = id;
            return ((SquirlearnWA.subcategoriaSOAP.Subcategoria)(this)).obtenerPorIdSubcategoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SquirlearnWA.subcategoriaSOAP.listarTodosSubcategoriaResponse SquirlearnWA.subcategoriaSOAP.Subcategoria.listarTodosSubcategoria(SquirlearnWA.subcategoriaSOAP.listarTodosSubcategoriaRequest request) {
            return base.Channel.listarTodosSubcategoria(request);
        }
        
        public SquirlearnWA.subcategoriaSOAP.subcategoriaDto[] listarTodosSubcategoria() {
            SquirlearnWA.subcategoriaSOAP.listarTodosSubcategoriaRequest inValue = new SquirlearnWA.subcategoriaSOAP.listarTodosSubcategoriaRequest();
            SquirlearnWA.subcategoriaSOAP.listarTodosSubcategoriaResponse retVal = ((SquirlearnWA.subcategoriaSOAP.Subcategoria)(this)).listarTodosSubcategoria(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SquirlearnWA.subcategoriaSOAP.listarTodosSubcategoriaResponse> SquirlearnWA.subcategoriaSOAP.Subcategoria.listarTodosSubcategoriaAsync(SquirlearnWA.subcategoriaSOAP.listarTodosSubcategoriaRequest request) {
            return base.Channel.listarTodosSubcategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SquirlearnWA.subcategoriaSOAP.listarTodosSubcategoriaResponse> listarTodosSubcategoriaAsync() {
            SquirlearnWA.subcategoriaSOAP.listarTodosSubcategoriaRequest inValue = new SquirlearnWA.subcategoriaSOAP.listarTodosSubcategoriaRequest();
            return ((SquirlearnWA.subcategoriaSOAP.Subcategoria)(this)).listarTodosSubcategoriaAsync(inValue);
        }
    }
}
