USE [mydb];
GO

/* ==========================================================================
   SECCIÓN DE LIMPIEZA (DROPS)
   ========================================================================== */

-- CATEGORIAS
DROP TRIGGER IF EXISTS TRG_CATEGORIAS_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_CATEGORIAS_UPDATE_AUDITORIA;
GO

-- COLORES
DROP TRIGGER IF EXISTS TRG_COLORES_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_COLORES_UPDATE_AUDITORIA;
GO

-- CONDICIONES
DROP TRIGGER IF EXISTS TRG_CONDICIONES_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_CONDICIONES_UPDATE_AUDITORIA;
GO

-- ESTADOS_CHATS
DROP TRIGGER IF EXISTS TRG_ESTADOS_CHATS_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_ESTADOS_CHATS_UPDATE_AUDITORIA;
GO

-- ESTADOS_ITEMS
DROP TRIGGER IF EXISTS TRG_ESTADOS_ITEMS_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_ESTADOS_ITEMS_UPDATE_AUDITORIA;
GO

-- ESTADOS_MENSAJES
DROP TRIGGER IF EXISTS TRG_ESTADOS_MENSAJES_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_ESTADOS_MENSAJES_UPDATE_AUDITORIA;
GO

-- ESTADOS_PERSONAS
DROP TRIGGER IF EXISTS TRG_ESTADOS_PERSONAS_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_ESTADOS_PERSONAS_UPDATE_AUDITORIA;
GO

-- ESTADOS_PUBLICACIONES
DROP TRIGGER IF EXISTS TRG_ESTADOS_PUBLICACIONES_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_ESTADOS_PUBLICACIONES_UPDATE_AUDITORIA;
GO

-- FORMAS_PAGO
DROP TRIGGER IF EXISTS TRG_FORMAS_PAGO_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_FORMAS_PAGO_UPDATE_AUDITORIA;
GO

-- FORMATOS
DROP TRIGGER IF EXISTS TRG_FORMATOS_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_FORMATOS_UPDATE_AUDITORIA;
GO

-- MONEDAS
DROP TRIGGER IF EXISTS TRG_MONEDAS_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_MONEDAS_UPDATE_AUDITORIA;
GO

-- MOTIVOS
DROP TRIGGER IF EXISTS TRG_MOTIVOS_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_MOTIVOS_UPDATE_AUDITORIA;
GO
--PERSONAS
DROP TRIGGER IF EXISTS TRG_PERSONAS_ROLES_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_PERSONAS_ROLES_UPDATE_AUDITORIA;
--SUBCATEGORIAS
DROP TRIGGER IF EXISTS TRG_SUBCATEGORIAS_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_SUBCATEGORIAS_UPDATE_AUDITORIA;
DROP TRIGGER IF EXISTS TRG_TAMANOS_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_TAMANOS_UPDATE_AUDITORIA;
DROP TRIGGER IF EXISTS TRG_ALQUILERES_INSERT_AUDITORIA;
DROP TRIGGER IF EXISTS TRG_ALQUILERES_UPDATE_AUDITORIA;
DROP TRIGGER IF EXISTS TRG_CHATS_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_CHATS_UPDATE_AUDITORIA;
DROP TRIGGER IF EXISTS TRG_COMPROBANTES_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_COMPROBANTES_UPDATE_AUDITORIA;
DROP TRIGGER IF EXISTS TRG_DETALLES_COMPROBANTES_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_DETALLES_COMPROBANTES_UPDATE_AUDITORIA;
DROP TRIGGER IF EXISTS TRG_PUBLICACIONES_INSERT_HISTORIA;
DROP TRIGGER IF EXISTS TRG_PUBLICACIONES_UPDATE_HISTORIA;
DROP TRIGGER IF EXISTS TRG_HISTORIAS_PUBLICACIONES_UPDATE_AUDITORIA;
DROP TRIGGER IF EXISTS TRG_INCIDENCIAS_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_INCIDENCIAS_UPDATE_AUDITORIA;
DROP TRIGGER IF EXISTS TRG_PERSONAS_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_PERSONAS_UPDATE_AUDITORIA;
DROP TRIGGER IF EXISTS TRG_PUBLICACIONES_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_PUBLICACIONES_UPDATE_AUDITORIA;
DROP TRIGGER IF EXISTS TRG_PUBLICACIONES_GESTION_ESTADOS;
DROP TRIGGER IF EXISTS TRG_MENSAJES_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_MENSAJES_UPDATE_LEIDO;
DROP TRIGGER IF EXISTS TRG_NOTIFICACIONES_CREATE_AUDITORIA;
DROP TRIGGER IF EXISTS TRG_NOTIFICACIONES_UPDATE_AUDITORIA;
DROP TRIGGER IF EXISTS TRG_ITEMS_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_ITEMS_UPDATE_AUDITORIA;
DROP TRIGGER IF EXISTS TRG_ROLES_INSERT_CREACION;
DROP TRIGGER IF EXISTS TRG_ROLES_UPDATE_AUDITORIA;
GO

/* ==========================================================================
   SECCIÓN DE CREACIÓN (TRIGGERS)
   hola, una aclaración es para el uso de JOIN, ssql maneja tablas virtuales 'inserted' y 'deleted' de la misma tabla.
   ========================================================================== */

/* CATEGORIAS */
CREATE TRIGGER TRG_CATEGORIAS_INSERT_CREACION ON dbo.categorias
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_CREACION = GETDATE(),
        USUARIO_CREACION = SYSTEM_USER
    FROM dbo.categorias t
    INNER JOIN inserted i ON t.CATEGORIA_ID = i.CATEGORIA_ID;
END
GO

CREATE TRIGGER TRG_CATEGORIAS_UPDATE_AUDITORIA ON dbo.categorias
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET 
        -- Si el nuevo es NULL, mantenemos el viejo (deleted). Si no, usamos el nuevo (inserted)
        USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        FECHA_MODIFICACION = GETDATE(),
        USUARIO_MODIFICACION = SYSTEM_USER
    FROM dbo.categorias t
    INNER JOIN inserted i ON t.CATEGORIA_ID = i.CATEGORIA_ID
    INNER JOIN deleted d ON t.CATEGORIA_ID = d.CATEGORIA_ID;
END
GO

/* COLORES */
CREATE TRIGGER TRG_COLORES_INSERT_CREACION ON dbo.colores
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_CREACION = GETDATE(), USUARIO_CREACION = SYSTEM_USER
    FROM dbo.colores t INNER JOIN inserted i ON t.COLOR_ID = i.COLOR_ID;
END
GO

CREATE TRIGGER TRG_COLORES_UPDATE_AUDITORIA ON dbo.colores
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        FECHA_MODIFICACION = GETDATE(), USUARIO_MODIFICACION = SYSTEM_USER
    FROM dbo.colores t 
    INNER JOIN inserted i ON t.COLOR_ID = i.COLOR_ID
    INNER JOIN deleted d ON t.COLOR_ID = d.COLOR_ID;
END
GO

/* CONDICIONES */
CREATE TRIGGER TRG_CONDICIONES_INSERT_CREACION ON dbo.condiciones
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_CREACION = GETDATE(), USUARIO_CREACION = SYSTEM_USER
    FROM dbo.condiciones t INNER JOIN inserted i ON t.CONDICION_ID = i.CONDICION_ID;
END
GO

CREATE TRIGGER TRG_CONDICIONES_UPDATE_AUDITORIA ON dbo.condiciones
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        FECHA_MODIFICACION = GETDATE(), USUARIO_MODIFICACION = SYSTEM_USER
    FROM dbo.condiciones t
    INNER JOIN inserted i ON t.CONDICION_ID = i.CONDICION_ID
    INNER JOIN deleted d ON t.CONDICION_ID = d.CONDICION_ID;
END
GO

/* ESTADOS_CHATS */
CREATE TRIGGER TRG_ESTADOS_CHATS_INSERT_CREACION ON dbo.estados_chats
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_CREACION = GETDATE(), USUARIO_CREACION = SYSTEM_USER
    FROM dbo.estados_chats t INNER JOIN inserted i ON t.ESTADOCHAT_ID = i.ESTADOCHAT_ID;
END
GO

CREATE TRIGGER TRG_ESTADOS_CHATS_UPDATE_AUDITORIA ON dbo.estados_chats
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        FECHA_MODIFICACION = GETDATE(), USUARIO_MODIFICACION = SYSTEM_USER
    FROM dbo.estados_chats t
    INNER JOIN inserted i ON t.ESTADOCHAT_ID = i.ESTADOCHAT_ID
    INNER JOIN deleted d ON t.ESTADOCHAT_ID = d.ESTADOCHAT_ID;
END
GO

/* ESTADOS_ITEMS */
CREATE TRIGGER TRG_ESTADOS_ITEMS_INSERT_CREACION ON dbo.estados_items
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_CREACION = GETDATE(), USUARIO_CREACION = SYSTEM_USER
    FROM dbo.estados_items t INNER JOIN inserted i ON t.ESTADOITEM_ID = i.ESTADOITEM_ID;
END
GO

CREATE TRIGGER TRG_ESTADOS_ITEMS_UPDATE_AUDITORIA ON dbo.estados_items
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        FECHA_MODIFICACION = GETDATE(), USUARIO_MODIFICACION = SYSTEM_USER
    FROM dbo.estados_items t
    INNER JOIN inserted i ON t.ESTADOITEM_ID = i.ESTADOITEM_ID
    INNER JOIN deleted d ON t.ESTADOITEM_ID = d.ESTADOITEM_ID;
END
GO

/* ESTADOS_MENSAJES */
CREATE TRIGGER TRG_ESTADOS_MENSAJES_INSERT_CREACION ON dbo.estados_mensajes
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_CREACION = GETDATE(), USUARIO_CREACION = SYSTEM_USER
    FROM dbo.estados_mensajes t INNER JOIN inserted i ON t.ESTADOMSJ_ID = i.ESTADOMSJ_ID;
END
GO

CREATE TRIGGER TRG_ESTADOS_MENSAJES_UPDATE_AUDITORIA ON dbo.estados_mensajes
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        FECHA_MODIFICACION = GETDATE(), USUARIO_MODIFICACION = SYSTEM_USER
    FROM dbo.estados_mensajes t
    INNER JOIN inserted i ON t.ESTADOMSJ_ID = i.ESTADOMSJ_ID
    INNER JOIN deleted d ON t.ESTADOMSJ_ID = d.ESTADOMSJ_ID;
END
GO

/* ESTADOS_PERSONAS */
CREATE TRIGGER TRG_ESTADOS_PERSONAS_INSERT_CREACION ON dbo.estados_personas
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_CREACION = GETDATE(), USUARIO_CREACION = SYSTEM_USER
    FROM dbo.estados_personas t INNER JOIN inserted i ON t.ESTADOPERSONA_ID = i.ESTADOPERSONA_ID;
END
GO

CREATE TRIGGER TRG_ESTADOS_PERSONAS_UPDATE_AUDITORIA ON dbo.estados_personas
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        FECHA_MODIFICACION = GETDATE(), USUARIO_MODIFICACION = SYSTEM_USER
    FROM dbo.estados_personas t
    INNER JOIN inserted i ON t.ESTADOPERSONA_ID = i.ESTADOPERSONA_ID
    INNER JOIN deleted d ON t.ESTADOPERSONA_ID = d.ESTADOPERSONA_ID;
END
GO

/* ESTADOS_PUBLICACIONES */
CREATE TRIGGER TRG_ESTADOS_PUBLICACIONES_INSERT_CREACION ON dbo.estados_publicaciones
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_CREACION = GETDATE(), USUARIO_CREACION = SYSTEM_USER
    FROM dbo.estados_publicaciones t INNER JOIN inserted i ON t.ESTADOPUBLI_ID = i.ESTADOPUBLI_ID;
END
GO

CREATE TRIGGER TRG_ESTADOS_PUBLICACIONES_UPDATE_AUDITORIA ON dbo.estados_publicaciones
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        FECHA_MODIFICACION = GETDATE(), USUARIO_MODIFICACION = SYSTEM_USER
    FROM dbo.estados_publicaciones t
    INNER JOIN inserted i ON t.ESTADOPUBLI_ID = i.ESTADOPUBLI_ID
    INNER JOIN deleted d ON t.ESTADOPUBLI_ID = d.ESTADOPUBLI_ID;
END
GO

/* FORMAS_PAGO */
CREATE TRIGGER TRG_FORMAS_PAGO_INSERT_CREACION ON dbo.formas_pago
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_CREACION = GETDATE(), USUARIO_CREACION = SYSTEM_USER
    FROM dbo.formas_pago t INNER JOIN inserted i ON t.FORMAPAGO_ID = i.FORMAPAGO_ID;
END
GO

CREATE TRIGGER TRG_FORMAS_PAGO_UPDATE_AUDITORIA ON dbo.formas_pago
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        FECHA_MODIFICACION = GETDATE(), USUARIO_MODIFICACION = SYSTEM_USER
    FROM dbo.formas_pago t
    INNER JOIN inserted i ON t.FORMAPAGO_ID = i.FORMAPAGO_ID
    INNER JOIN deleted d ON t.FORMAPAGO_ID = d.FORMAPAGO_ID;
END
GO

/* FORMATOS */
CREATE TRIGGER TRG_FORMATOS_INSERT_CREACION ON dbo.formatos
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_CREACION = GETDATE(), USUARIO_CREACION = SYSTEM_USER
    FROM dbo.formatos t INNER JOIN inserted i ON t.FORMATO_ID = i.FORMATO_ID;
END
GO

CREATE TRIGGER TRG_FORMATOS_UPDATE_AUDITORIA ON dbo.formatos
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        FECHA_MODIFICACION = GETDATE(), USUARIO_MODIFICACION = SYSTEM_USER
    FROM dbo.formatos t
    INNER JOIN inserted i ON t.FORMATO_ID = i.FORMATO_ID
    INNER JOIN deleted d ON t.FORMATO_ID = d.FORMATO_ID;
END
GO

/* MONEDAS */
CREATE TRIGGER TRG_MONEDAS_INSERT_CREACION ON dbo.monedas
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_CREACION = GETDATE(), USUARIO_CREACION = SYSTEM_USER
    FROM dbo.monedas t INNER JOIN inserted i ON t.MONEDA_ID = i.MONEDA_ID;
END
GO

CREATE TRIGGER TRG_MONEDAS_UPDATE_AUDITORIA ON dbo.monedas
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        FECHA_MODIFICACION = GETDATE(), USUARIO_MODIFICACION = SYSTEM_USER
    FROM dbo.monedas t
    INNER JOIN inserted i ON t.MONEDA_ID = i.MONEDA_ID
    INNER JOIN deleted d ON t.MONEDA_ID = d.MONEDA_ID;
END
GO

/* MOTIVOS */
CREATE TRIGGER TRG_MOTIVOS_INSERT_CREACION ON dbo.motivos
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_CREACION = GETDATE(), USUARIO_CREACION = SYSTEM_USER
    FROM dbo.motivos t INNER JOIN inserted i ON t.MOTIVO_ID = i.MOTIVO_ID;
END
GO

CREATE TRIGGER TRG_MOTIVOS_UPDATE_AUDITORIA ON dbo.motivos
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        FECHA_MODIFICACION = GETDATE(), USUARIO_MODIFICACION = SYSTEM_USER
    FROM dbo.motivos t
    INNER JOIN inserted i ON t.MOTIVO_ID = i.MOTIVO_ID
    INNER JOIN deleted d ON t.MOTIVO_ID = d.MOTIVO_ID;
END
GO

/* PERSONAS_ROLES */
CREATE TRIGGER TRG_PERSONAS_ROLES_INSERT_CREACION ON dbo.personas_roles
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_CREACION = GETDATE(), USUARIO_CREACION = SYSTEM_USER
    FROM dbo.personas_roles t INNER JOIN inserted i ON t.PERSONA_ID = i.PERSONA_ID AND t.ROLPERSONA_ID = i.ROLPERSONA_ID;
END
GO

CREATE TRIGGER TRG_PERSONAS_ROLES_UPDATE_AUDITORIA ON dbo.personas_roles
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        FECHA_MODIFICACION = GETDATE(), USUARIO_MODIFICACION = SYSTEM_USER
    FROM dbo.personas_roles t
    INNER JOIN inserted i ON t.PERSONA_ID = i.PERSONA_ID AND t.ROLPERSONA_ID = i.ROLPERSONA_ID
    INNER JOIN deleted d ON t.PERSONA_ID = d.PERSONA_ID AND t.ROLPERSONA_ID = d.ROLPERSONA_ID;
END
GO

/* SUBCATEGORIAS */
CREATE TRIGGER TRG_SUBCATEGORIAS_INSERT_CREACION ON dbo.subcategorias
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_CREACION = GETDATE(), USUARIO_CREACION = SYSTEM_USER
    FROM dbo.subcategorias t INNER JOIN inserted i ON t.SUBCATEGORIA_ID = i.SUBCATEGORIA_ID AND t.CATEGORIA_ID = i.CATEGORIA_ID;
END
GO

CREATE TRIGGER TRG_SUBCATEGORIAS_UPDATE_AUDITORIA ON dbo.subcategorias
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        FECHA_MODIFICACION = GETDATE(), USUARIO_MODIFICACION = SYSTEM_USER
    FROM dbo.subcategorias t
    INNER JOIN inserted i ON t.SUBCATEGORIA_ID = i.SUBCATEGORIA_ID
    INNER JOIN deleted d ON t.SUBCATEGORIA_ID = d.SUBCATEGORIA_ID;
END
GO

/* TAMANOS */
CREATE TRIGGER TRG_TAMANOS_INSERT_CREACION ON dbo.tamanos
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_CREACION = GETDATE(), USUARIO_CREACION = SYSTEM_USER
    FROM dbo.tamanos t INNER JOIN inserted i ON t.TAMANO_ID = i.TAMANO_ID;
END
GO

CREATE TRIGGER TRG_TAMANOS_UPDATE_AUDITORIA ON dbo.tamanos
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        FECHA_MODIFICACION = GETDATE(), USUARIO_MODIFICACION = SYSTEM_USER
    FROM dbo.tamanos t
    INNER JOIN inserted i ON t.TAMANO_ID = i.TAMANO_ID
    INNER JOIN deleted d ON t.TAMANO_ID = d.TAMANO_ID;
END
GO

/* ALQUILERES */
CREATE TRIGGER TRG_ALQUILERES_INSERT_AUDITORIA ON dbo.alquileres
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    -- Usuario viene del front, solo seteamos fecha
    UPDATE t
    SET FECHA_CREACION = GETDATE()
    FROM dbo.alquileres t INNER JOIN inserted i ON t.ALQUILER_ID = i.ALQUILER_ID;
END
GO

CREATE TRIGGER TRG_ALQUILERES_UPDATE_AUDITORIA ON dbo.alquileres
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        FECHA_MODIFICACION = GETDATE(), USUARIO_MODIFICACION = SYSTEM_USER
    FROM dbo.alquileres t
    INNER JOIN inserted i ON t.ALQUILER_ID = i.ALQUILER_ID
    INNER JOIN deleted d ON t.ALQUILER_ID = d.ALQUILER_ID;
END
GO

/* CHATS */
CREATE TRIGGER TRG_CHATS_INSERT_CREACION ON dbo.chats
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    -- Usuario viene del front
    UPDATE t
    SET FECHA_CREACION = GETDATE()
    FROM dbo.chats t INNER JOIN inserted i ON t.CHAT_ID = i.CHAT_ID;
END
GO

CREATE TRIGGER TRG_CHATS_UPDATE_AUDITORIA ON dbo.chats
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        FECHA_MODIFICACION = GETDATE() -- Aquí no pusiste usuario modif en el original, respeto eso
    FROM dbo.chats t
    INNER JOIN inserted i ON t.CHAT_ID = i.CHAT_ID
    INNER JOIN deleted d ON t.CHAT_ID = d.CHAT_ID;
END
GO

/* COMPROBANTES */
CREATE TRIGGER TRG_COMPROBANTES_INSERT_CREACION ON dbo.comprobantes
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_EMISION = ISNULL(i.FECHA_EMISION, GETDATE()), -- Si es null, pone hoy
        FECHA_CREACION = GETDATE()
    FROM dbo.comprobantes t INNER JOIN inserted i ON t.COMPROBANTE_ID = i.COMPROBANTE_ID;
END
GO

CREATE TRIGGER TRG_COMPROBANTES_UPDATE_AUDITORIA ON dbo.comprobantes
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        FECHA_MODIFICACION = GETDATE(), USUARIO_MODIFICACION = SYSTEM_USER
    FROM dbo.comprobantes t
    INNER JOIN inserted i ON t.COMPROBANTE_ID = i.COMPROBANTE_ID
    INNER JOIN deleted d ON t.COMPROBANTE_ID = d.COMPROBANTE_ID;
END
GO

/* DETALLES_COMPROBANTES */
CREATE TRIGGER TRG_DETALLES_COMPROBANTES_INSERT_CREACION ON dbo.detalles_comprobantes
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_CREACION = GETDATE()
    FROM dbo.detalles_comprobantes t 
    INNER JOIN inserted i ON t.DETALLECOM_ID = i.DETALLECOM_ID;
END
GO

CREATE TRIGGER TRG_DETALLES_COMPROBANTES_UPDATE_AUDITORIA ON dbo.detalles_comprobantes
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        FECHA_MODIFICACION = GETDATE(), USUARIO_MODIFICACION = SYSTEM_USER
    FROM dbo.detalles_comprobantes t
    INNER JOIN inserted i ON t.DETALLECOM_ID = i.DETALLECOM_ID
    INNER JOIN deleted d ON t.DETALLECOM_ID = d.DETALLECOM_ID;
END
GO

/* HISTORIAS_PUBLICACIONES Y LÓGICA DE NEGOCIO PUBLICACIONES */

-- 1. Insertar Historia al Crear Publicación
CREATE TRIGGER TRG_PUBLICACIONES_INSERT_HISTORIA ON dbo.publicaciones
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO dbo.historias_publicaciones (
        PUBLICACION_ID,
        ESTADO_ID_ANTERIOR, ITEM_ID_ITEM_ANTERIOR,
        ESTADO_ID_ACTUAL, ITEM_ID_ITEM_ACTUAL,
        USUARIO_MODIFICACION_PUBLICACION, FECHA_MODIFICACION_PUBLICACION
    )
    SELECT 
        i.PUBLICACION_ID,
        NULL, NULL, -- Anterior
        i.ESTADO_PUBLICACION_ID, i.ITEM_ID_ITEM, -- Actual
        i.USUARIO_CREACION, GETDATE()
    FROM inserted i;
END
GO

-- 3. Insertar Historia al Modificar Publicación
CREATE TRIGGER TRG_PUBLICACIONES_UPDATE_HISTORIA ON dbo.publicaciones
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO dbo.historias_publicaciones (
        PUBLICACION_ID,
        ESTADO_ID_ANTERIOR, ITEM_ID_ITEM_ANTERIOR,
        ESTADO_ID_ACTUAL, ITEM_ID_ITEM_ACTUAL,
        USUARIO_MODIFICACION_PUBLICACION, FECHA_MODIFICACION_PUBLICACION
    )
    SELECT 
        i.PUBLICACION_ID,
        d.ESTADO_PUBLICACION_ID, d.ITEM_ID_ITEM, 
        i.ESTADO_PUBLICACION_ID, i.ITEM_ID_ITEM, 
        i.USUARIO_MODIFICACION, GETDATE()
    FROM inserted i
    INNER JOIN deleted d ON i.PUBLICACION_ID = d.PUBLICACION_ID
    WHERE i.ESTADO_PUBLICACION_ID <> d.ESTADO_PUBLICACION_ID 
       OR i.ITEM_ID_ITEM <> d.ITEM_ID_ITEM;
END
GO

-- 4. Auditoría de la propia tabla de Historia
CREATE TRIGGER TRG_HISTORIAS_PUBLICACIONES_UPDATE_AUDITORIA ON dbo.historias_publicaciones
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_MODIFICACION = GETDATE(), USUARIO_MODIFICACION = SYSTEM_USER
    FROM dbo.historias_publicaciones t INNER JOIN inserted i ON t.HISTORIAPUBLI_ID = i.HISTORIAPUBLI_ID;
END
GO

/* INCIDENCIAS */
CREATE TRIGGER TRG_INCIDENCIAS_INSERT_CREACION ON dbo.incidencias
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_CREACION = GETDATE()
    FROM dbo.incidencias t INNER JOIN inserted i ON t.INCIDENCIA_ID = i.INCIDENCIA_ID;
END
GO

CREATE TRIGGER TRG_INCIDENCIAS_UPDATE_AUDITORIA ON dbo.incidencias
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        -- Lógica de resolución: Si cambió a 1, ponemos fecha solución
        FECHA_SOLUCION = CASE 
                            WHEN i.RESUELTO = 1 AND d.RESUELTO <> 1 THEN GETDATE()
                            ELSE t.FECHA_SOLUCION 
                         END,
        FECHA_MODIFICACION = GETDATE(),
        USUARIO_MODIFICACION = SYSTEM_USER
    FROM dbo.incidencias t
    INNER JOIN inserted i ON t.INCIDENCIA_ID = i.INCIDENCIA_ID
    INNER JOIN deleted d ON t.INCIDENCIA_ID = d.INCIDENCIA_ID;
END
GO

/* PERSONAS */
CREATE TRIGGER TRG_PERSONAS_INSERT_CREACION ON dbo.personas
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_CREACION = GETDATE()
    FROM dbo.personas t INNER JOIN inserted i ON t.PERSONA_ID = i.PERSONA_ID;
END
GO

CREATE TRIGGER TRG_PERSONAS_UPDATE_AUDITORIA ON dbo.personas
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        FECHA_MODIFICACION = GETDATE()
    FROM dbo.personas t
    INNER JOIN inserted i ON t.PERSONA_ID = i.PERSONA_ID
    INNER JOIN deleted d ON t.PERSONA_ID = d.PERSONA_ID;
END
GO

/* PUBLICACIONES (Auditoría Básica) */
CREATE TRIGGER TRG_PUBLICACIONES_INSERT_CREACION ON dbo.publicaciones
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_CREACION = GETDATE()
    FROM dbo.publicaciones t INNER JOIN inserted i ON t.PUBLICACION_ID = i.PUBLICACION_ID;
END
GO

CREATE TRIGGER TRG_PUBLICACIONES_UPDATE_AUDITORIA ON dbo.publicaciones
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        FECHA_MODIFICACION = GETDATE()
    FROM dbo.publicaciones t
    INNER JOIN inserted i ON t.PUBLICACION_ID = i.PUBLICACION_ID
    INNER JOIN deleted d ON t.PUBLICACION_ID = d.PUBLICACION_ID;
END
GO

/* PUBLICACIONES (Cambio de Estado) */
CREATE TRIGGER TRG_PUBLICACIONES_GESTION_ESTADOS
ON dbo.publicaciones
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    -- =========================================================================
    -- ESCUDO ANTI-RECURSIVIDAD
    -- Si este trigger ya está corriendo (nivel > 1), nos salimos para no repetir.
    -- =========================================================================
    IF ((SELECT TRIGGER_NESTLEVEL()) > 1) RETURN;

    -- Solo trabajamos si la columna de ESTADO fue modificada
    IF UPDATE(ESTADO_PUBLICACION_ID)
    BEGIN
        -- LÓGICA 1: Si pasa a 'Aprobada' (ID 2) y no tiene fecha, poner FECHA_ALTA
        UPDATE p
        SET FECHA_ALTA = GETDATE()
        FROM dbo.publicaciones p
        INNER JOIN inserted i ON p.PUBLICACION_ID = i.PUBLICACION_ID
        INNER JOIN deleted d ON p.PUBLICACION_ID = d.PUBLICACION_ID
        -- Hacemos JOIN con estados para asegurar por Nombre o por ID
        INNER JOIN dbo.estados_publicaciones ep ON i.ESTADO_PUBLICACION_ID = ep.ESTADOPUBLI_ID
        WHERE i.ESTADO_PUBLICACION_ID <> d.ESTADO_PUBLICACION_ID -- El estado cambió
          AND (upper(ep.NOMBRE) = 'APROBADA' OR i.ESTADO_PUBLICACION_ID = 2)
          AND i.FECHA_ALTA IS NULL;

        -- LÓGICA 2: Si pasa a 'Eliminada' (ID 4) y no tiene fecha, poner FECHA_BAJA
        UPDATE p
        SET FECHA_BAJA = GETDATE()
        FROM dbo.publicaciones p
        INNER JOIN inserted i ON p.PUBLICACION_ID = i.PUBLICACION_ID
        INNER JOIN deleted d ON p.PUBLICACION_ID = d.PUBLICACION_ID
        INNER JOIN dbo.estados_publicaciones ep ON i.ESTADO_PUBLICACION_ID = ep.ESTADOPUBLI_ID
        WHERE i.ESTADO_PUBLICACION_ID <> d.ESTADO_PUBLICACION_ID -- El estado cambió
          AND (upper(ep.NOMBRE) = 'ELIMINADA' OR i.ESTADO_PUBLICACION_ID = 4)
          AND i.FECHA_BAJA IS NULL;
    END
END
GO

/* MENSAJES */
CREATE TRIGGER TRG_MENSAJES_INSERT_CREACION ON dbo.mensajes
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_CREACION = GETDATE(),
        USUARIO_CREACION = SYSTEM_USER,
        -- Si estado = 1 (Enviado), poner fecha envio
        FECHA_ENVIO = CASE WHEN i.ESTADO_MSJ_ID = 1 THEN GETDATE() ELSE t.FECHA_ENVIO END
    FROM dbo.mensajes t 
    INNER JOIN inserted i ON t.MENSAJE_ID = i.MENSAJE_ID;
END
GO

CREATE TRIGGER TRG_MENSAJES_UPDATE_LEIDO ON dbo.mensajes
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        -- Si estado cambió a 3 (Leído), poner fecha leido
        FECHA_LEIDO = CASE WHEN i.ESTADO_MSJ_ID = 3 THEN GETDATE() ELSE t.FECHA_LEIDO END,
        FECHA_MODIFICACION = GETDATE(),
        USUARIO_MODIFICACION = SYSTEM_USER
    FROM dbo.mensajes t
    INNER JOIN inserted i ON t.MENSAJE_ID = i.MENSAJE_ID
    INNER JOIN deleted d ON t.MENSAJE_ID = d.MENSAJE_ID;
END
GO

/* NOTIFICACIONES */
CREATE TRIGGER TRG_NOTIFICACIONES_CREATE_AUDITORIA ON dbo.notificaciones
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA = GETDATE()
    FROM dbo.notificaciones t 
    INNER JOIN inserted i ON t.NOTIFICACION_ID = i.NOTIFICACION_ID;
END
GO

CREATE TRIGGER TRG_NOTIFICACIONES_UPDATE_AUDITORIA ON dbo.notificaciones
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_MODIFICACION = GETDATE(), USUARIO_MODIFICACION = SYSTEM_USER
    FROM dbo.notificaciones t 
    INNER JOIN inserted i ON t.NOTIFICACION_ID = i.NOTIFICACION_ID;
END
GO

/* ITEMS */
CREATE TRIGGER TRG_ITEMS_INSERT_CREACION ON dbo.items
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET FECHA_CREACION = GETDATE()
    FROM dbo.items t 
    INNER JOIN inserted i ON t.ITEM_ID = i.ITEM_ID;
END
GO

CREATE TRIGGER TRG_ITEMS_UPDATE_AUDITORIA ON dbo.items
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        FECHA_MODIFICACION = GETDATE()
    FROM dbo.items t
    INNER JOIN inserted i ON t.ITEM_ID = i.ITEM_ID
    INNER JOIN deleted d ON t.ITEM_ID = d.ITEM_ID;
END
GO

/* ROLES */
CREATE TRIGGER TRG_ROLES_INSERT_CREACION ON dbo.roles
AFTER INSERT AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = SYSTEM_USER, FECHA_CREACION = GETDATE()
    FROM dbo.roles t 
    INNER JOIN inserted i ON t.ROLPERSONA_ID = i.ROLPERSONA_ID;
END
GO

CREATE TRIGGER TRG_ROLES_UPDATE_AUDITORIA ON dbo.roles
AFTER UPDATE AS
BEGIN
    SET NOCOUNT ON;
    UPDATE t
    SET USUARIO_CREACION = ISNULL(i.USUARIO_CREACION, d.USUARIO_CREACION),
        FECHA_CREACION = ISNULL(i.FECHA_CREACION, d.FECHA_CREACION),
        FECHA_MODIFICACION = GETDATE(), USUARIO_MODIFICACION = SYSTEM_USER
    FROM dbo.roles t
    INNER JOIN inserted i ON t.ROLPERSONA_ID = i.ROLPERSONA_ID
    INNER JOIN deleted d ON t.ROLPERSONA_ID = d.ROLPERSONA_ID;
END
GO